# Analysis

Sentiment, categorization, clustering, and Plotly exploration for discovery records.

**Prereq:** `python3 setup/extract_records.py` so `output/processed/challenges.csv` and `expectations.csv` exist.

In [13]:
%pip install -q -r requirements.txt
%pip install -q "nbformat>=4.2.0"

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.

In [14]:
from pathlib import Path
import sys

import hdbscan
import numpy as np
import pandas as pd
import plotly.express as px
import umap
from IPython.display import Markdown, display
from sklearn.metrics import silhouette_score

sys.path.insert(0, str(Path(".").resolve()))
from setup.analyze_records import (
    CATEGORY_CONFIG,
    CATEGORY_DESCRIPTIONS,
    realign_by_sentiment,
    run_categorize,
    run_sentiment,
)
from setup.extract_records import SOURCE_MEETING_NOTES, load_prepared_records

CHALLENGES_CSV = Path("./output/processed/challenges.csv")
EXPECTATIONS_CSV = Path("./output/processed/expectations.csv")
PROCESSED_DIR = Path("./output/processed")

CHALLENGES_SCORED = PROCESSED_DIR / "challenges_scored.csv"
EXPECTATIONS_SCORED = PROCESSED_DIR / "expectations_scored.csv"
CATEGORIZED_CHALLENGES_CSV = PROCESSED_DIR / "categorized_challenges.csv"
CATEGORIZED_EXPECTATIONS_CSV = PROCESSED_DIR / "categorized_expectations.csv"
CATEGORY_SUMMARY_CSV = PROCESSED_DIR / "category_summary.csv"

CHALLENGE_TEXT_COL = "pain_points"
EXPECTATION_TEXT_COL = "expectations"

## 1. Load & prep records

Loads CSVs via `load_prepared_records()` (focus-group aliases, source tags, short meeting-note merge).

In [15]:
df_painpoints, df_expectations = load_prepared_records(
    CHALLENGES_CSV, EXPECTATIONS_CSV
)

print(f"Challenges: {len(df_painpoints)} | Expectations: {len(df_expectations)}")
print(df_painpoints["source"].value_counts().to_string())

  Redacted stakeholder names (78 dictionary entries → [PERSON])
Challenges: 1110 | Expectations: 375
source
meeting_notes    914
worksheet        196

## 2. Sentiment

Uses `Thi144/sentiment-distilbert-7class`, mapped to negative / neutral / positive.

In [16]:
df_painpoints, df_expectations = run_sentiment(df_painpoints, df_expectations)

print("Pain sentiment:\n", df_painpoints["sentiment"].value_counts().to_string())
print("\nExpectation sentiment:\n", df_expectations["sentiment"].value_counts().to_string())

df_painpoints.to_csv(CHALLENGES_SCORED, index=False, encoding="utf-8-sig")
df_expectations.to_csv(EXPECTATIONS_SCORED, index=False, encoding="utf-8-sig")
print(f"Saved → {CHALLENGES_SCORED.name}, {EXPECTATIONS_SCORED.name}")

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Scoring challenges…
Scoring expectations…
Pain sentiment:
 sentiment
negative    895
positive    215

Expectation sentiment:
 sentiment
positive    334
negative     41
Saved → challenges_scored.csv, expectations_scored.csv

## 3. Realign misclassified rows

Move positive “pain” → expectations and negative “expectations” → pain, **meeting_notes only**.

In [17]:
n_pos = int(
    ((df_painpoints["source"] == SOURCE_MEETING_NOTES) & (df_painpoints["sentiment"] == "positive")).sum()
)
n_neg = int(
    ((df_expectations["source"] == SOURCE_MEETING_NOTES) & (df_expectations["sentiment"] == "negative")).sum()
)

df_painpoints, df_expectations = realign_by_sentiment(
    df_painpoints, df_expectations, only_source=SOURCE_MEETING_NOTES
)

print(f"Moved meeting_notes only: {n_pos} positive→expectations, {n_neg} negative→pain")
print(f"Shapes: pain {len(df_painpoints)}, expectations {len(df_expectations)}")
print(df_painpoints["source"].value_counts().to_string())

Moved meeting_notes only: 195 positive→expectations, 22 negative→pain
Shapes: pain 937, expectations 548
source
meeting_notes    741
worksheet        196

## 4. Categorize records

Hybrid: title keywords → body keywords → semantic similarity.

In [18]:
df, expectations_df, challenge_embeddings, embedder = run_categorize(
    df_painpoints, df_expectations
)

print("Challenge categories:\n", df["Category"].value_counts().to_string())
print("\nExpectation categories:\n", expectations_df["Category"].value_counts().to_string())

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/15 [00:00<?, ?it/s]

Batches:   0%|          | 0/9 [00:00<?, ?it/s]

Challenge categories:
 Category
Records & Document Management       207
Case Management                     199
System Integration                  126
User Experience & Performance        93
Communication & Collaboration        88
Workflow & Business Processes        76
Scheduling & Resource Management     60
Data Management & Visibility         51
Training & Documentation             21
Reporting & Decision Support         16

Expectation categories:
 Category
Records & Document Management       132
Case Management                     103
System Integration                   82
Communication & Collaboration        54
User Experience & Performance        45
Workflow & Business Processes        40
Scheduling & Resource Management     30
Data Management & Visibility         29
Reporting & Decision Support         18
Training & Documentation             15

## 5. Cluster challenges (UMAP + HDBSCAN)

In [26]:
def assign_cluster_names(
    frame: pd.DataFrame,
    cluster_col: str = "Cluster",
    category_col: str = "Category",
    output_col: str = "Cluster_Label",
) -> tuple[pd.DataFrame, pd.DataFrame]:
    cluster_summary = (
        frame.groupby([cluster_col, category_col]).size().reset_index(name="Count")
    )
    dominant = (
        cluster_summary.sort_values("Count", ascending=False)
        .drop_duplicates(subset=[cluster_col])
        [[cluster_col, category_col]]
        .rename(columns={category_col: output_col})
    )
    return frame.merge(dominant, on=cluster_col, how="left"), cluster_summary


def soft_assign_noise(
    coords: np.ndarray,
    labels: np.ndarray,
    radius_percentile: float = 92,
    radius_slack: float = 1.35,
) -> tuple[np.ndarray, int]:
    """Pull leftover noise into the nearest cluster if it sits inside that cluster's envelope."""
    out = labels.copy()
    clustered = out != -1
    if not clustered.any():
        return out, 0

    centroids, radii = {}, {}
    for cid in sorted(set(out[clustered])):
        pts = coords[out == cid]
        centroids[cid] = pts.mean(axis=0)
        dists = np.linalg.norm(pts - centroids[cid], axis=1)
        radii[cid] = float(np.percentile(dists, radius_percentile) * radius_slack)

    assigned = 0
    for i in np.where(out == -1)[0]:
        best_c, best_d = None, np.inf
        for cid, center in centroids.items():
            d = float(np.linalg.norm(coords[i] - center))
            if d < best_d:
                best_c, best_d = cid, d
        if best_c is not None and best_d <= radii[best_c]:
            out[i] = best_c
            assigned += 1
    return out, assigned


TARGET_CLUSTERS = len(CATEGORY_CONFIG)
# Prefer coverage over ultra-tight cores (prior sweep left ~36% as noise).
NOISE_PENALTY = 1.35
CLUSTER_COUNT_PENALTY = 0.012

reducer = umap.UMAP(
    n_neighbors=15, n_components=12, min_dist=0.0, metric="cosine", random_state=42
)
reduced = reducer.fit_transform(challenge_embeddings)

candidate_params = sorted(
    {
        (mcs, ms, method)
        for mcs in range(5, 14)
        for ms in (1, 2, 3, max(1, mcs // 3))
        for method in ("eom", "leaf")
    }
)

sweep_rows, best_labels, best_params, best_score = [], None, None, -np.inf
n_rows = max(len(df), 1)
for mcs, ms, method in candidate_params:
    labels = hdbscan.HDBSCAN(
        min_cluster_size=mcs,
        min_samples=ms,
        metric="euclidean",
        cluster_selection_method=method,
    ).fit_predict(reduced)

    mask = labels != -1
    n_clusters = len(set(labels[mask]))
    noise = int((labels == -1).sum())
    noise_frac = noise / n_rows
    silhouette = (
        silhouette_score(reduced[mask], labels[mask], metric="euclidean")
        if mask.sum() > 1 and n_clusters > 1
        else -1.0
    )
    # Reject near-all-noise or absurd fragmentation early.
    if noise_frac > 0.45 or n_clusters < 4 or n_clusters > 40:
        combined = -1.0
    else:
        combined = (
            silhouette
            - abs(n_clusters - TARGET_CLUSTERS) * CLUSTER_COUNT_PENALTY
            - noise_frac * NOISE_PENALTY
        )
    sweep_rows.append({
        "min_cluster_size": mcs,
        "min_samples": ms,
        "method": method,
        "clusters": n_clusters,
        "noise": noise,
        "noise_pct": round(noise_frac * 100, 1),
        "silhouette": round(float(silhouette), 4),
        "combined_score": round(float(combined), 4),
    })
    if combined > best_score:
        best_score, best_labels, best_params = combined, labels, (mcs, ms, method)

print("Best HDBSCAN params:", best_params, "score:", round(float(best_score), 4))
display(pd.DataFrame(sweep_rows).sort_values("combined_score", ascending=False).head(10))

raw_labels = best_labels.copy()
raw_noise = int((raw_labels == -1).sum())
best_labels, n_soft = soft_assign_noise(reduced, best_labels)
print(
    f"Soft-assigned {n_soft} noise points into nearest clusters "
    f"(noise {raw_noise} → {int((best_labels == -1).sum())})"
)

df["Cluster_Raw"] = raw_labels
df["Cluster"] = best_labels
df["Assign_Status"] = np.where(
    raw_labels != -1,
    "HDBSCAN cluster",
    np.where(best_labels != -1, "Soft-assigned", "Unclustered"),
)
df, cluster_summary = assign_cluster_names(df)
df.loc[df["Cluster"] == -1, "Cluster_Label"] = "Noise / unclustered"

print("\nAssignment status:")
print(df["Assign_Status"].value_counts().to_string())
print("\nCluster → label counts:")
print(df.groupby(["Cluster", "Cluster_Label"]).size().to_string())
print(
    f"\nUnclustered: {(df['Cluster'] == -1).sum()} / {len(df)} "
    f"({100 * (df['Cluster'] == -1).mean():.1f}%)"
)

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Best HDBSCAN params: (13, 4, 'eom') score: 0.0506

,min_cluster_size,min_samples,method,clusters,noise,noise_pct,silhouette,combined_score
56,13,4,eom,19,193,20.6,0.4367,0.0506
42,12,1,eom,24,160,17.1,0.4395,0.0409
50,13,1,eom,23,172,18.4,0.4404,0.0366
48,12,4,eom,21,234,25.0,0.4942,0.0251
38,11,2,eom,25,173,18.5,0.4535,0.0242
44,12,2,eom,24,184,19.6,0.4545,0.0214
52,13,2,eom,23,196,20.9,0.4551,0.0167
51,13,1,leaf,24,205,21.9,0.4800,0.0166
26,9,2,eom,27,164,17.5,0.4492,0.0089
32,10,2,eom,27,164,17.5,0.4492,0.0089

Soft-assigned 64 noise points into nearest clusters (noise 193 → 129)

Assignment status:
Assign_Status
HDBSCAN cluster    744
Unclustered        129
Soft-assigned       64

Cluster → label counts:
Cluster  Cluster_Label
-1       Noise / unclustered    129

Unclustered: 129 / 937 (13.8%)

### Soft assignment map

2D projection of the same UMAP space used for HDBSCAN. Color by assignment status to see which points were dense cores, which were rescued by soft assignment, and which stayed unclustered.

### Cluster contents

Browse every cluster for dissection, including noise (`Cluster == -1`).

In [29]:
cols = [
    c
    for c in [
        "Cluster",
        "Cluster_Label",
        "Assign_Status",
        "focus_group",
        CHALLENGE_TEXT_COL,
        "Category",
        "source",
    ]
    if c in df.columns
]
show = df[cols].sort_values(["Cluster", "Assign_Status", "focus_group"]).reset_index(drop=True)

print("Cluster sizes (including unclustered):")
display(
    show.groupby(["Cluster", "Cluster_Label"], as_index=False)
    .size()
    .rename(columns={"size": "Count"})
    .sort_values("Cluster")
)

for cid, group in show.groupby("Cluster", sort=True):
    label = group["Cluster_Label"].iloc[0]
    display(Markdown(f"### Cluster {cid} — {label} ({len(group)} records)"))
    display(
        group[[c for c in ["focus_group", CHALLENGE_TEXT_COL, "Category", "source"] if c in group.columns]]
        .reset_index(drop=True)
    )

Cluster sizes (including unclustered):

   Cluster        Cluster_Label  Count
0       -1  Noise / unclustered    129

### Cluster -1 — Noise / unclustered (129 records)

,focus_group,pain_points,Category,source
0,Admin Aide,Sometimes Rent Holds / Rent Release doesn't ap...,Scheduling & Resource Management,worksheet
1,Admin Aide,They could edit it on their end,Communication & Collaboration,meeting_notes
2,Admin Aide,His work around – said Law verify address,Records & Document Management,meeting_notes
3,Admin Aide,Spell check or grammar check,Records & Document Management,meeting_notes
4,Admin Aide,Issue with feature – put in a complaint under ...,Case Management,meeting_notes
...,...,...,...,...
124,Zoning,Lot aleration,Workflow & Business Processes,worksheet
125,Zoning,Basement filling system (excel spreadsheet),Workflow & Business Processes,worksheet
126,Zoning,"Communication: applicant, reviewer",Communication & Collaboration,worksheet
127,Zoning,Biggest weakness with inspectors – proactive e...,Workflow & Business Processes,meeting_notes
128,Zoning,Side project with this – enterprise system wit...,System Integration,meeting_notes

### Cluster 0 — nan (15 records)

,focus_group,pain_points,Category,source
0,Admin Aide,"J: AS400 – uses it for water billing, goes to ...",System Integration,meeting_notes
1,Admin Aide,"AS400: Do use it often, very outdated",System Integration,meeting_notes
2,Admin Aide,[PERSON] not really trained on AS400,System Integration,meeting_notes
3,Building Inspectors,Difficult for AS400 to use,System Integration,meeting_notes
4,Building Inspectors,[PERSON] – liked AS400 – had everything in there,System Integration,meeting_notes
5,Building Inspectors,"AS400 checks 4 way – [PERSON] uses constantly,...",System Integration,meeting_notes
6,Building Inspectors,Several inspectors do not have access to AS400...,System Integration,meeting_notes
7,Housing Inspectors,Then send to aide to put in AS400,System Integration,meeting_notes
8,IT,Common with health firm - 80-90k for support o...,Training & Documentation,meeting_notes
9,Law,Inability to access water records without AS400,Records & Document Management,worksheet
10,NBD Internal,Tools: No OnBase access. No AS400 access. IPS ...,System Integration,meeting_notes
11,Permit/Commercial/Electrical Inspectors,AS400 – checking ownership and activity – don'...,System Integration,meeting_notes
12,Supervisors,Can't access directly from within the system,System Integration,meeting_notes
13,Supervisors,Right now – still need to go into AS400,System Integration,meeting_notes
14,Zoning,Going through three systems not including pape...,System Integration,meeting_notes

### Cluster 1 — nan (28 records)

,focus_group,pain_points,Category,source
0,Admin Aide,Filling out appointments separately,Communication & Collaboration,worksheet
1,Admin Aide,S: Scheduling When person supposed to be in a ...,Scheduling & Resource Management,meeting_notes
2,Admin Aide,Scheduling appointment – that is alphabetized,Scheduling & Resource Management,meeting_notes
3,Admin Aide,Each appointment – have to schedule in 2-3 pla...,Scheduling & Resource Management,meeting_notes
4,Admin Aide,Mondays are the busiest – 9 or 3pm,Scheduling & Resource Management,meeting_notes
5,Admin Aide,Closing/Next Steps | 5min | [PERSON],Communication & Collaboration,meeting_notes
6,BAA Operations,Have 3 different Outlook calendars for hearing...,Scheduling & Resource Management,meeting_notes
7,BAA Supervisors,Currently – doing virtual in teams and schedul...,Scheduling & Resource Management,meeting_notes
8,BAA Supervisors,"Ideally could schedule across BAA, inspector, PO",Scheduling & Resource Management,meeting_notes
9,BAA Supervisors,Same with calls MS Teams for virtual hearings,Communication & Collaboration,meeting_notes
10,Building Inspectors,If you're interrupted AS400 you can look up mi...,System Integration,meeting_notes
11,CPO-Coordinators,Would also force owners to schedule and not sa...,Communication & Collaboration,meeting_notes
12,Fire,Scheduling - need to be put in multiple places,Scheduling & Resource Management,worksheet
13,Fire,Automatically add an assignment would be nice,Case Management,meeting_notes
14,Fire,Scheduling – having to go into MS Outlook – ad...,Scheduling & Resource Management,meeting_notes
15,Housing Inspectors,Anywhere from 1-2 times a day to a few times a...,Scheduling & Resource Management,meeting_notes
16,Housing Inspectors,Would save hours to be able to do it in the field,Records & Document Management,meeting_notes
17,IT,[PERSON] Get exact same phone calls for city o...,Communication & Collaboration,meeting_notes
18,OCHD,Neaverly? - came up at HUD conference,Communication & Collaboration,meeting_notes
19,OCHD,[PERSON] schedules for referrals by phone,Case Management,meeting_notes
20,Permit/Commercial/Electrical Inspectors,Seeing new/assigned work,Scheduling & Resource Management,worksheet
21,Permit/Commercial/Electrical Inspectors,Do their 90% of their own scheduling,Scheduling & Resource Management,meeting_notes
22,Permit/Commercial/Electrical Inspectors,Do – make their own schedule,Scheduling & Resource Management,meeting_notes
23,Permit/Commercial/Electrical Inspectors,They created their own schedules,Scheduling & Resource Management,meeting_notes
24,Permit/Commercial/Electrical Inspectors,If someone leaves – takes of 200 cases – break...,Case Management,meeting_notes
25,Permit/Commercial/Electrical Inspectors,Shows up in schedule twice,Scheduling & Resource Management,meeting_notes
26,Permits,[PERSON] gets calls in July – print list of si...,Communication & Collaboration,meeting_notes
27,Permits,Chuck did first one 1.5 months ago,Scheduling & Resource Management,meeting_notes

### Cluster 2 — nan (110 records)

,focus_group,pain_points,Category,source
0,Admin Aide,Periodic Insp module for Rental Registry – ann...,User Experience & Performance,meeting_notes
1,Admin Aide,Mainly put under Prop Maint Int/Ext - would be...,Case Management,meeting_notes
2,Admin Aide,When waiting on approval for something – if th...,Workflow & Business Processes,meeting_notes
3,Admin Aide,Likes periodics window for Rental Registry,Records & Document Management,meeting_notes
4,Admin Aide,Attachment for CofUs – don't see it in the att...,Records & Document Management,meeting_notes
...,...,...,...,...
105,CPO-Coordinators,[PERSON] having to duplicate things from Camin...,System Integration,meeting_notes
106,OCHD,[PERSON] flagged that city has new system of r...,Case Management,meeting_notes
107,Permit/Commercial/Electrical Inspectors,Ask clerks for that,Records & Document Management,meeting_notes
108,Permit/Commercial/Electrical Inspectors,Not as tech savvy – miss IPS – likes the tickl...,Scheduling & Resource Management,meeting_notes
109,Zoning,Disconnected – permit review touches other dep...,Case Management,meeting_notes

### Cluster 3 — nan (18 records)

,focus_group,pain_points,Category,source
0,Admin Aide,Phone calls dropping,Communication & Collaboration,worksheet
1,Admin Aide,Prolonged loading time,User Experience & Performance,worksheet
2,Admin Aide,Our phones are on a time limit – 5min max – dr...,Communication & Collaboration,meeting_notes
3,Admin Aide,20 calls dropped between 4 of them one week,Communication & Collaboration,meeting_notes
4,Admin Aide,20min wasted time due to phones,Communication & Collaboration,meeting_notes
5,Admin Aide,Only more annoying because,User Experience & Performance,meeting_notes
6,BAA ALJs,Repeating data entry,Data Management & Visibility,worksheet
7,BAA Operations,Repeat same information,Data Management & Visibility,worksheet
8,BAA Operations,Mila: Don't see the point in repeating informa...,Records & Document Management,meeting_notes
9,Housing Inspectors,Re-enter info when that happens,Scheduling & Resource Management,meeting_notes
10,Housing Inspectors,Take a bunch of pictures – use work phone for ...,Communication & Collaboration,meeting_notes
11,IT,RTL – recovery time is going to be biggest cha...,Scheduling & Resource Management,meeting_notes
12,IT,RPO is low – maybe an hour,Scheduling & Resource Management,meeting_notes
13,IT,When moved onto new hardware from a few years ...,User Experience & Performance,meeting_notes
14,Supervisors,Sending phone screenshots of documents frustra...,Communication & Collaboration,meeting_notes
15,Zoning,Re-subs,System Integration,worksheet
16,Zoning,Answering repetitive phone calls,Communication & Collaboration,worksheet
17,BAA Operations,Time consuming to parse through,User Experience & Performance,meeting_notes

### Cluster 4 — nan (58 records)

,focus_group,pain_points,Category,source
0,Admin Aide,Default options in complaint module always pre...,User Experience & Performance,meeting_notes
1,Admin Aide,Owner/contact information – needs to be connec...,Case Management,meeting_notes
2,Admin Aide,Adds in complaint module,User Experience & Performance,meeting_notes
3,BAA ALJs,Cannot pull a case up with violation number,Case Management,worksheet
4,BAA ALJs,"[PERSON] Related cases, whether prior cases of...",Case Management,meeting_notes
5,BAA ALJs,Not associated to particular code violations e...,Case Management,meeting_notes
6,BAA ALJs,"Apr 1 violations , Apr 4 violations can be rec...",Case Management,meeting_notes
7,BAA ALJs,Have to look up cases by case number – would b...,Case Management,meeting_notes
8,BAA ALJs,"Overview page – overview of violations, number...",Case Management,meeting_notes
9,BAA Operations,Search case when client doesn't have a violati...,Case Management,worksheet
10,BAA Operations,Violation searches: have to search for address...,Records & Document Management,worksheet
11,BAA Supervisors,Inability to parse out multiple violations = e...,Case Management,worksheet
12,BAA Supervisors,Individual complaint cases – can't see overarc...,Case Management,meeting_notes
13,BAA Supervisors,[PERSON] cases not linked is top frustration,Case Management,meeting_notes
14,BAA Supervisors,"When there's multiple violations, it gets cumb...",Case Management,meeting_notes
15,BAA Supervisors,Can't tell which picture goes to which violati...,Data Management & Visibility,meeting_notes
16,BAA Supervisors,Ideally: infestation photo – violation – what ...,Data Management & Visibility,meeting_notes
17,BAA Supervisors,If someone wants to know the open violations –...,Case Management,meeting_notes
18,BAA Supervisors,"Default D&Os – adding fine amounts, violations...",Case Management,meeting_notes
19,CPC,Open / closed symbols on complaints,Case Management,worksheet
20,CPC,Violation sheet mixed with everything else,Case Management,worksheet
21,CPC,Search by ticket number and violation number,Case Management,worksheet
22,CPC,Currently only allows search by ticket number,Records & Document Management,worksheet
23,CPC,Dan: Icon for whether violation is open or clo...,Case Management,meeting_notes
24,CPC,Symbols of open/closed slows them down,User Experience & Performance,meeting_notes
25,CPC,Can search by complaint number,Records & Document Management,meeting_notes
26,CPC,One ticket number could have multiple violatio...,Case Management,meeting_notes
27,CPC,Would like to see way to search by violation n...,Records & Document Management,meeting_notes
28,CPC,Technology – Dislikes Way to make violation nu...,Case Management,meeting_notes
29,Fire,Researching history of violations is time cons...,Case Management,worksheet
30,Fire,Issues/Frustrations Can group permits using ca...,Case Management,meeting_notes
31,Housing Inspectors,When others are entering violations at the sam...,Case Management,worksheet
32,Housing Inspectors,Entering violations – simultaneous entry – ask...,Case Management,meeting_notes
33,Housing Inspectors,Exterior violations – trash or overgrowth – 10...,Case Management,meeting_notes
34,Housing Inspectors,When select OG – entering same info for every ...,Case Management,meeting_notes
35,Housing Inspectors,That's one where violation is always the same ...,Case Management,meeting_notes
36,Housing Inspectors,If there is a violation – enter into complaint...,Case Management,meeting_notes
37,IT,Maybe only look at what's active within a year,Records & Document Management,meeting_notes
38,Law,Cannot combine open violations from multiple c...,Case Management,worksheet
39,NBD Data Team,"J: we link cases to gether, CA link to Code co...",Case Management,meeting_notes
40,NBD Data Team,J: violations: SPCC code book. After adding we...,Case Management,meeting_notes
41,NBD Internal,"When in a complaint case, when trying to put a...",Case Management,meeting_notes
42,Office Managers,Technology Likes Search by complaint number,Records & Document Management,meeting_notes
43,Office Managers,Would be nice to be able to search by violatio...,Records & Document Management,meeting_notes
44,Permits,Applicants can't view their own violation in t...,Case Management,meeting_notes
45,Permits,For violations – a lot of the same,Case Management,meeting_notes
46,Permits,Doesn't timestamp violation notes – if note le...,Case Management,meeting_notes
47,Permits,Search violations by type – broad categories e...,Case Management,meeting_notes
48,Permits,"As of April 1, 2025 – started charging for ROW...",Case Management,meeting_notes
49,Permits,Several different violations within that one i...,Case Management,meeting_notes
50,Permits,DPW citing ROW violations on spot and charging...,Case Management,meeting_notes
51,Supervisors,[PERSON] Requests certain reports – linking vi...,Case Management,meeting_notes
52,Zoning,Fields are separate – if type in 200 salina – ...,Records & Document Management,meeting_notes
53,Zoning,Questions about what's actually permitted,Training & Documentation,meeting_notes
54,Building Inspectors,DPW had their own cases in IPS when they first...,Case Management,meeting_notes
55,CPC,When a property has many violations- it loads ...,Case Management,worksheet
56,OCHD,Deb uses it to generate a PDF of violations – ...,Records & Document Management,meeting_notes
57,Supervisors,Flag if no activity in a month,Scheduling & Resource Management,meeting_notes

### Cluster 5 — nan (90 records)

,focus_group,pain_points,Category,source
0,Admin Aide,J: IPS crashing Loud sighs BAA ticketing – pro...,Workflow & Business Processes,meeting_notes
1,Admin Aide,Find ticket – make a single character edit,Case Management,meeting_notes
2,Admin Aide,BAA inconsistent – send back tickets for takin...,Case Management,meeting_notes
3,Admin Aide,BAA tried to send to PO Box – didn't go throug...,Case Management,meeting_notes
4,Admin Aide,Death certificate 2003 of someone trying to serve,Records & Document Management,meeting_notes
...,...,...,...,...
85,Permit/Commercial/Electrical Inspectors,Refer to BAA and Law,Records & Document Management,meeting_notes
86,Permit/Commercial/Electrical Inspectors,50% of people they write up go BAA/Law,Records & Document Management,meeting_notes
87,Permit/Commercial/Electrical Inspectors,Since they don't talk – cross referencing of e...,Communication & Collaboration,meeting_notes
88,Supervisors,Ticket scanner for setouts,Scheduling & Resource Management,meeting_notes
89,BAA ALJs,Decision bank – e..g defaults – someone doesn'...,Reporting & Decision Support,meeting_notes

### Cluster 6 — nan (22 records)

,focus_group,pain_points,Category,source
0,Admin Aide,Only use 2 out of the 20 options – actions in ...,User Experience & Performance,meeting_notes
1,Admin Aide,PI module layout – likes it better than the co...,User Experience & Performance,meeting_notes
2,Admin Aide,Likes the layout Only complaint is the list al...,Case Management,meeting_notes
3,BAA ALJs,Navigating between multiple screens,User Experience & Performance,worksheet
4,BAA ALJs,Too many windows,User Experience & Performance,worksheet
5,BAA ALJs,Navigating between screens is cumbersome. Some...,User Experience & Performance,meeting_notes
6,BAA ALJs,"Too many windows – better layout, user interfa...",User Experience & Performance,meeting_notes
7,BAA Operations,Actions log is so hard to understand,Workflow & Business Processes,worksheet
8,BAA Operations,There are so many tabs that aren't used,User Experience & Performance,worksheet
9,BAA Supervisors,Multiple “actions” not being used,Workflow & Business Processes,worksheet
10,Building Inspectors,Happens often – too many windows open,User Experience & Performance,meeting_notes
11,Housing Inspectors,Selection same actions multiple times,Workflow & Business Processes,worksheet
12,Housing Inspectors,Too many actions,Workflow & Business Processes,worksheet
13,Housing Inspectors,“Trim down” the drop downs related to assigned...,Case Management,worksheet
14,Housing Inspectors,"Reduce the drop-down – too many actions, too m...",Workflow & Business Processes,meeting_notes
15,NBD Internal,Add/remove entry options to customize data entry,Data Management & Visibility,meeting_notes
16,NBD Internal,It does feel a little – interface is outdated ...,System Integration,meeting_notes
17,Supervisors,[PERSON] doesn't like that it's on-prem – need...,User Experience & Performance,meeting_notes
18,Supervisors,Mobile version Software won't fix everything,User Experience & Performance,meeting_notes
19,Zoning,OnBase layout and windows often not very user-...,System Integration,worksheet
20,BAA ALJs,No ““how to” within the system – part of it ma...,User Experience & Performance,meeting_notes
21,Permits,Too many applications,System Integration,worksheet

### Cluster 7 — nan (18 records)

,focus_group,pain_points,Category,source
0,Admin Aide,Not consistent – some parts have features and ...,User Experience & Performance,meeting_notes
1,IT,Print log folder – has everything that was eve...,Records & Document Management,meeting_notes
2,NBD Internal,"We enter info, we don't rely on public. So, it...",System Integration,meeting_notes
3,Permits,Want historical information – hard to track an...,Data Management & Visibility,meeting_notes
4,Supervisors,Missing information / data (historical informa...,Data Management & Visibility,worksheet
5,Supervisors,“Some historical data lost in fire/flooding/pi...,Data Management & Visibility,worksheet
6,Supervisors,Information not digital/in one place,Data Management & Visibility,worksheet
7,Supervisors,Historical information is missing,Data Management & Visibility,worksheet
8,Supervisors,Researching in general – would be nice to do o...,Records & Document Management,meeting_notes
9,Supervisors,Missing information – records missing or uncle...,Data Management & Visibility,meeting_notes
10,Supervisors,Data and historical info not digital or in one...,Data Management & Visibility,meeting_notes
11,Zoning,Historical context / research scattered all ov...,Data Management & Visibility,worksheet
12,Zoning,“gaps” in information,Data Management & Visibility,worksheet
13,Zoning,Histories are done – word doc in a folder,Records & Document Management,meeting_notes
14,Zoning,Histories – expectations of what you're lookin...,Records & Document Management,meeting_notes
15,Fire,"Multiple ways/places to document – action, ima...",Case Management,worksheet
16,IT,How do we digitize microfiche or paper records?,Records & Document Management,meeting_notes
17,IT,City did that once – DPW digitized microfoche,Records & Document Management,meeting_notes

### Cluster 8 — nan (113 records)

,focus_group,pain_points,Category,source
0,Admin Aide,Difficult to find individual complaints,Case Management,worksheet
1,Admin Aide,Managing multiple tools – is that frustrating?...,System Integration,meeting_notes
2,Admin Aide,S: Doesn't use Excel on day to day,Reporting & Decision Support,meeting_notes
3,Admin Aide,Collaboration with other departments?,Communication & Collaboration,meeting_notes
4,BAA ALJs,Initial user frustration (learning curve),User Experience & Performance,worksheet
...,...,...,...,...
108,Fire,Use physical notepad or surface pro – then dat...,Data Management & Visibility,meeting_notes
109,Housing Inspectors,Would be helpful to categorize the follow up,Communication & Collaboration,meeting_notes
110,Housing Inspectors,Organizing those similar tasks – would be help...,Records & Document Management,meeting_notes
111,Housing Inspectors,Not any training materials,Training & Documentation,meeting_notes
112,Permits,Report capabilities would be important for fut...,Reporting & Decision Support,meeting_notes

### Cluster 9 — nan (29 records)

,focus_group,pain_points,Category,source
0,Admin Aide,Can't upload attachments,Records & Document Management,worksheet
1,Admin Aide,M: Unhandled exception error – entered complai...,User Experience & Performance,meeting_notes
2,Admin Aide,Computer is slow – takes 45 sec to open compla...,User Experience & Performance,meeting_notes
3,Admin Aide,Save button never in the same place or,User Experience & Performance,meeting_notes
4,Admin Aide,Everything else runs pretty smoothly – mainly ...,User Experience & Performance,meeting_notes
5,Admin Aide,If updating nail and mails – sometimes you can...,Records & Document Management,meeting_notes
6,Assessment,Every now and then issue of something not load...,User Experience & Performance,meeting_notes
7,BAA Supervisors,Volume too high MS Word for every template or ...,Workflow & Business Processes,meeting_notes
8,Building Inspectors,Couldn't save documents in there – had to go i...,System Integration,meeting_notes
9,Building Inspectors,If you try to delete causes issues,User Experience & Performance,meeting_notes
10,Building Inspectors,When it crashes – if it could refresh with whe...,User Experience & Performance,meeting_notes
11,CPO-Coordinators,60day notices: crashes and takes time to process,User Experience & Performance,worksheet
12,CPO-Coordinators,Printing out 60-day renewal notices – doesn't ...,Scheduling & Resource Management,meeting_notes
13,Housing Inspectors,"Have to click into 5-6 different cases, which ...",Case Management,meeting_notes
14,Housing Inspectors,Had laptop for awhile – very helpful – connect...,User Experience & Performance,meeting_notes
15,IT,"Space issues File uploaded, assigned global us...",Records & Document Management,meeting_notes
16,IT,If internet problem or non-supported file type...,User Experience & Performance,meeting_notes
17,IT,No time Biggest issues are related to database...,User Experience & Performance,meeting_notes
18,IT,Anything an issue due to user error?,User Experience & Performance,meeting_notes
19,Law,"Documents not loaded, notes needed",Records & Document Management,worksheet
20,OCHD,Sometimes system freezes Appreciate that every...,User Experience & Performance,meeting_notes
21,Office Managers,Sanitation notice bar in print queue crashes w...,User Experience & Performance,worksheet
22,Office Managers,Sanitation notice bar in print queue – 2500 le...,Records & Document Management,meeting_notes
23,Office Managers,"If you accidentally click it, it crashes",User Experience & Performance,meeting_notes
24,Office Managers,When you try to remove all it just spins and n...,Case Management,meeting_notes
25,Office Managers,Sometimes if print queue open all day – sessio...,Workflow & Business Processes,meeting_notes
26,Permit/Commercial/Electrical Inspectors,Every other day can't close completion form be...,User Experience & Performance,meeting_notes
27,Permits,In camino when application uploads the wrong d...,Records & Document Management,worksheet
28,Zoning,History searches take a significant amount of ...,Records & Document Management,worksheet

### Cluster 10 — nan (28 records)

,focus_group,pain_points,Category,source
0,Admin Aide,Finding/opening specific cases difficult,Case Management,meeting_notes
1,Admin Aide,When you open a case note on an already open c...,Case Management,meeting_notes
2,BAA Operations,Case notes not submitted in one spot,Case Management,worksheet
3,BAA Supervisors,Case not linked into inputted in one case not ...,Case Management,worksheet
4,Building Inspectors,Too many cases that they manage,Case Management,meeting_notes
5,Building Inspectors,County lead in there too – can see it – but ma...,Case Management,meeting_notes
6,Building Inspectors,Reggie's case changed – he tries to change the...,Case Management,meeting_notes
7,Building Inspectors,Same property – multiple cases,Case Management,meeting_notes
8,Building Inspectors,[PERSON] had skyline at the time – 45 minutes ...,Case Management,meeting_notes
9,Building Inspectors,[PERSON] has high hopes – this meeting longer ...,Communication & Collaboration,meeting_notes
10,Housing Inspectors,Organize cases based on type of cases,Case Management,worksheet
11,Housing Inspectors,No shortcut for common actions (i.e. code staf...,Records & Document Management,worksheet
12,Housing Inspectors,Bad layout Would be helpful if click on a case...,Case Management,meeting_notes
13,Housing Inspectors,Parkside – brings up many cases,Case Management,meeting_notes
14,Housing Inspectors,Doesn't auto-populate their name in the case –...,Case Management,meeting_notes
15,Housing Inspectors,[PERSON] puts his cases into a spreadsheet to ...,Workflow & Business Processes,meeting_notes
16,Law,When looking through a case number – if anythi...,Case Management,meeting_notes
17,NBD Internal,Sometimes doesn't have access – name doesn't s...,Case Management,meeting_notes
18,Office Managers,Especially if so many cases,Case Management,meeting_notes
19,Permit/Commercial/Electrical Inspectors,“Impossible Piece of Shit” called it initially...,Case Management,meeting_notes
20,Permits,Two versions of the same case,Case Management,meeting_notes
21,Supervisors,Closing older cases – case clean up needed,Case Management,meeting_notes
22,Supervisors,Open cases from staff that don't work here any...,Case Management,meeting_notes
23,Supervisors,Change in process – something changed where it...,Case Management,meeting_notes
24,Supervisors,No way to batch update cases,Case Management,meeting_notes
25,Supervisors,Analyze properties or cases /owners,Case Management,meeting_notes
26,BAA Supervisors,On that date/time - pop up and record and auto...,Case Management,meeting_notes
27,Housing Inspectors,60 cases some days,Case Management,meeting_notes

### Cluster 11 — nan (28 records)

,focus_group,pain_points,Category,source
0,Admin Aide,Sometimes it saves sometimes it doesn't; diffe...,System Integration,worksheet
1,Admin Aide,Saving an inspection after scheduling crashes ...,User Experience & Performance,worksheet
2,Admin Aide,Freezing and crashing of IPS,User Experience & Performance,worksheet
3,Admin Aide,IPS crash 2-3 times per day,User Experience & Performance,meeting_notes
4,Admin Aide,S: Limit on tabs IPS can handle- multi-task – ...,User Experience & Performance,meeting_notes
5,Admin Aide,IPS: when trying to save anything – brink of c...,User Experience & Performance,meeting_notes
6,BAA Supervisors,[PERSON] still gets IPS notification from orig...,Communication & Collaboration,meeting_notes
7,BAA Supervisors,IPS freezes every now and then,User Experience & Performance,meeting_notes
8,Housing Inspectors,When IPS freezes or not working efficiently it...,User Experience & Performance,worksheet
9,Housing Inspectors,Actions in IPS are slow to select,User Experience & Performance,worksheet
10,Housing Inspectors,IPS will be slow or shutdown; reboot needed,User Experience & Performance,worksheet
11,Housing Inspectors,IPS slow or needs to be rebooted,User Experience & Performance,meeting_notes
12,Housing Inspectors,Loading button – IPS spinning – automatically ...,User Experience & Performance,meeting_notes
13,Housing Inspectors,Used IPS on tablet once when first started – c...,User Experience & Performance,meeting_notes
14,Housing Inspectors,IPS app was confusing – connection issues as well,User Experience & Performance,meeting_notes
15,IT,IPS died once before – 10 years ago – physical...,User Experience & Performance,meeting_notes
16,NBD Internal,IPS runs slow when doing mass data entry – may...,User Experience & Performance,meeting_notes
17,Office Managers,Opening cases too quickly and more than one at...,User Experience & Performance,worksheet
18,Office Managers,"If IPS open too long, it crashes – usually has...",User Experience & Performance,meeting_notes
19,Permit/Commercial/Electrical Inspectors,IPS buffers/breaks down,System Integration,worksheet
20,Permit/Commercial/Electrical Inspectors,IPS crashes sometimes – little issues here and...,User Experience & Performance,meeting_notes
21,Permit/Commercial/Electrical Inspectors,Doesn't like RR module in IPS,User Experience & Performance,meeting_notes
22,Permits,Internal disconnect of notifications,Communication & Collaboration,meeting_notes
23,Permits,IPS: No unit in IPS,System Integration,meeting_notes
24,Permits,IPS – search for new build,Records & Document Management,meeting_notes
25,Zoning,"IPS slowness, larger parcels have issues takin...",Records & Document Management,worksheet
26,Zoning,Switching between IPS and OnBase so often beca...,System Integration,meeting_notes
27,IT,Downtime translates to users not able to do th...,Scheduling & Resource Management,meeting_notes

### Cluster 12 — nan (62 records)

,focus_group,pain_points,Category,source
0,Admin Aide,IPS doesn't allow saving owner addresses somet...,Case Management,meeting_notes
1,Admin Aide,Dark mode for IPS? +2 Incredibly bright,System Integration,meeting_notes
2,BAA ALJs,No full access to IPS,System Integration,worksheet
3,BAA ALJs,Cannot easily rename files in IPS,Workflow & Business Processes,worksheet
4,BAA ALJs,"Sue is PT ALJ, in once per week. Learning curv...",Workflow & Business Processes,meeting_notes
...,...,...,...,...
57,Fire,Capabilities they wish IPS had,System Integration,meeting_notes
58,Law,I can't complete an affirmation if the notices...,Records & Document Management,worksheet
59,Permit/Commercial/Electrical Inspectors,At one point had IPS tablets – check to see if...,User Experience & Performance,meeting_notes
60,Permits,IPS – would be nice to be notified of approval...,Communication & Collaboration,meeting_notes
61,Permits,Capabilities they wish IPS had,System Integration,meeting_notes

### Cluster 13 — nan (51 records)

,focus_group,pain_points,Category,source
0,Admin Aide,Inspector names listed for periodic inspection...,Scheduling & Resource Management,worksheet
1,Admin Aide,Inspector names not alphabetized,Scheduling & Resource Management,meeting_notes
2,Admin Aide,Inspection schedule and inspection note,Scheduling & Resource Management,meeting_notes
3,Admin Aide,"Building, Fire, Electrical – schedule each ind...",Scheduling & Resource Management,meeting_notes
4,Admin Aide,4-5 properties scheduling inspections for – ca...,Scheduling & Resource Management,meeting_notes
5,Admin Aide,"Problem because inspector should sign, then in...",Workflow & Business Processes,meeting_notes
6,Admin Aide,Inspectors update SeeClick Fix – not admin aides,Reporting & Decision Support,meeting_notes
7,Admin Aide,Periodic inspections module: Issue with inspec...,Case Management,meeting_notes
8,Assessment,"For Assessment's purposes as a viewer, has met...",Records & Document Management,meeting_notes
9,BAA Operations,Inspections tab needs to contain more things,Case Management,worksheet
10,BAA Supervisors,Schedule inspection at point there's a hearing...,Case Management,meeting_notes
11,Building Inspectors,Task to be done for inspection addressed befor...,Case Management,worksheet
12,Building Inspectors,Water check – gets another inspector to look u...,Workflow & Business Processes,meeting_notes
13,Building Inspectors,Photos also helpful for inspectors – compare/c...,Records & Document Management,meeting_notes
14,Building Inspectors,Fire will also start their own cases in IPS – ...,Case Management,meeting_notes
15,Fire,From reviewers/inspections,Case Management,worksheet
16,Fire,Inspectors use a writable PDF inspection form ...,Records & Document Management,meeting_notes
17,Fire,Actions versus inspections – some people don't...,Case Management,meeting_notes
18,Fire,Need a data person for Fire,Data Management & Visibility,meeting_notes
19,Housing Inspectors,Could be tailored to just housing inspections,Case Management,meeting_notes
20,Housing Inspectors,Inspection results – real close in the drop-do...,Case Management,meeting_notes
21,Housing Inspectors,Periodic inspection – inspector names not in a...,Scheduling & Resource Management,meeting_notes
22,Law,Inspectors don't always take good records,Records & Document Management,worksheet
23,Law,If an inspector has missed anything -,Records & Document Management,meeting_notes
24,OCHD,Inspection scheduling? Inspections for childre...,Case Management,meeting_notes
25,Office Managers,Option for action update to inspector – to aut...,Communication & Collaboration,meeting_notes
26,Permit/Commercial/Electrical Inspectors,[PERSON] Primarily dealing with contractors,Communication & Collaboration,meeting_notes
27,Permit/Commercial/Electrical Inspectors,"Inspections – photos, notes",Case Management,meeting_notes
28,Permit/Commercial/Electrical Inspectors,Residential electrical – previously done by co...,Records & Document Management,meeting_notes
29,Permit/Commercial/Electrical Inspectors,Work directly with Fire department – they work...,Communication & Collaboration,meeting_notes
30,Permit/Commercial/Electrical Inspectors,Commercial – fire working hand in hand with pe...,Case Management,meeting_notes
31,Permit/Commercial/Electrical Inspectors,5 inspections in a day,Case Management,meeting_notes
32,Permit/Commercial/Electrical Inspectors,"Check footers, framing, electrical",Records & Document Management,meeting_notes
33,Permit/Commercial/Electrical Inspectors,Format is better Couldn't do periodic inspecti...,Case Management,meeting_notes
34,Permit/Commercial/Electrical Inspectors,Going backwards Building inspectors – down peo...,Communication & Collaboration,meeting_notes
35,Permit/Commercial/Electrical Inspectors,Projects can go on for,Scheduling & Resource Management,meeting_notes
36,Permit/Commercial/Electrical Inspectors,Residential guys – can be completed in 3 month...,Scheduling & Resource Management,meeting_notes
37,Permit/Commercial/Electrical Inspectors,"There's a backlog of stuff, especially roofs o...",Scheduling & Resource Management,meeting_notes
38,Permits,Inspectors in two worlds now,Communication & Collaboration,meeting_notes
39,Supervisors,Or simple as not putting yourself in the inspe...,Case Management,meeting_notes
40,Supervisors,Screwed if we get audited,Records & Document Management,meeting_notes
41,Supervisors,Major issues for contractors - applications,Scheduling & Resource Management,meeting_notes
42,Admin Aide,Not all explicitly told at the same time who i...,Communication & Collaboration,meeting_notes
43,BAA Supervisors,Periodic inspections Multiple rounds of ticket...,Case Management,meeting_notes
44,BAA Supervisors,Notes section can get chaotic – so much data i...,Case Management,meeting_notes
45,Housing Inspectors,Lapses – happened more at old building,Communication & Collaboration,meeting_notes
46,OCHD,Modules and demos on Inspect2Go website,User Experience & Performance,meeting_notes
47,Office Managers,Inspector complaint for BAA – length it takes ...,Case Management,meeting_notes
48,Permit/Commercial/Electrical Inspectors,Warmer dryer weather – c,Scheduling & Resource Management,meeting_notes
49,Permits,Age old question – print all reviewer comments...,Communication & Collaboration,meeting_notes
50,Supervisors,Older system – missed assignment run – could r...,Scheduling & Resource Management,meeting_notes

### Cluster 14 — nan (23 records)

,focus_group,pain_points,Category,source
0,Building Inspectors,Elevator certification,Training & Documentation,worksheet
1,Building Inspectors,Water certification,Training & Documentation,worksheet
2,Building Inspectors,Nob Hill – cited over 2 years ago for elevator...,Scheduling & Resource Management,meeting_notes
3,Building Inspectors,"Third-party inspectors: Sprinklers, fire alarm...",Records & Document Management,meeting_notes
4,Building Inspectors,Technology See the water and elevator certs – ...,Training & Documentation,meeting_notes
5,Building Inspectors,i.e. Can't finish the CofC application until t...,Workflow & Business Processes,meeting_notes
6,Fire,Eventually adding Fire alarms (starting to be ...,Training & Documentation,meeting_notes
7,Law,If no N&M – need to do whole process over,Workflow & Business Processes,meeting_notes
8,NBD Internal,Time spent pull that info and making sure info...,Records & Document Management,meeting_notes
9,OCHD,Lack of ability to request inspection on-deman...,Communication & Collaboration,meeting_notes
10,OCHD,Internal Access database for tracking inspecti...,Case Management,meeting_notes
11,OCHD,Confusing to know whether property has active ...,User Experience & Performance,meeting_notes
12,Office Managers,"Property cited June 1 ,warning letter 14, refe...",Records & Document Management,meeting_notes
13,Permit/Commercial/Electrical Inspectors,At the end of the – generate paperwork for CO ...,Case Management,meeting_notes
14,Permit/Commercial/Electrical Inspectors,Told by vendor they could do periodic inspecti...,Case Management,meeting_notes
15,Permit/Commercial/Electrical Inspectors,Up to permitting person to contact inspectors ...,Records & Document Management,meeting_notes
16,Permit/Commercial/Electrical Inspectors,For HVAC – some are using third party companie...,Scheduling & Resource Management,meeting_notes
17,Permit/Commercial/Electrical Inspectors,Needs to assign CofC but don't put their name ...,Communication & Collaboration,meeting_notes
18,Permits,Notification to code enforcement applicants an...,Case Management,worksheet
19,Zoning,That info needs to be available to the inspect...,Records & Document Management,meeting_notes
20,Permit/Commercial/Electrical Inspectors,Internal due dates – the owner is notified – t...,Scheduling & Resource Management,meeting_notes
21,Zoning,Late in process,Workflow & Business Processes,worksheet
22,Zoning,Code inspectors – proactive with enforcement o...,Records & Document Management,meeting_notes

### Cluster 15 — nan (15 records)

,focus_group,pain_points,Category,source
0,Admin Aide,Deed search – if inspectors listed with parcel...,Records & Document Management,meeting_notes
1,Admin Aide,Katelyn creates tickets Re: mailing a letter o...,Records & Document Management,meeting_notes
2,BAA ALJs,Should come up during property liens/tax searc...,Records & Document Management,meeting_notes
3,BAA ALJs,Not every attorney knows to come to Dept of Fi...,Records & Document Management,meeting_notes
4,BAA Operations,Tools County Clerk for deeds,Records & Document Management,meeting_notes
5,BAA Supervisors,Ideally would be able to view by property and/...,Records & Document Management,meeting_notes
6,BAA Supervisors,County Clerk deed look-up,Records & Document Management,meeting_notes
7,CPC,Tax Trusts – repayment agreement for delinquen...,Records & Document Management,meeting_notes
8,Housing Inspectors,County – name or address would pull up all inf...,Records & Document Management,meeting_notes
9,NBD Internal,Property research: inability to pull informati...,Records & Document Management,worksheet
10,NBD Internal,[PERSON] Accessing County Clerk database is on...,Records & Document Management,meeting_notes
11,OCHD,Real Property tax database,Records & Document Management,meeting_notes
12,OCHD,Owner information - County Clerk office doesn'...,Case Management,meeting_notes
13,OCHD,Workaround for that issue? When they find the ...,Case Management,meeting_notes
14,Office Managers,Workaround – county map will put you onto the ...,Records & Document Management,meeting_notes

### Cluster 16 — nan (48 records)

,focus_group,pain_points,Category,source
0,Admin Aide,Would save time if all info on catchment map w...,Records & Document Management,meeting_notes
1,Admin Aide,Can they have assessment update the address?,Records & Document Management,meeting_notes
2,Admin Aide,Assessment change of address form – share,Records & Document Management,meeting_notes
3,Admin Aide,Main place where parcel is,Records & Document Management,meeting_notes
4,BAA Supervisors,Too many interfaces not linking info (i.e. par...,Records & Document Management,worksheet
5,BAA Supervisors,Address search less reliable – ideally would b...,Records & Document Management,meeting_notes
6,BAA Supervisors,Which apartment of the structure is cited? Dis...,Records & Document Management,meeting_notes
7,BAA Supervisors,Image Mate Online – assessed owner addresses,Case Management,meeting_notes
8,CPC,Property addresses same in eTax – shared asses...,Records & Document Management,meeting_notes
9,CPO-Coordinators,Parcel search can be tricky,Records & Document Management,meeting_notes
10,CPO-Coordinators,For food vendors or peddler – don't know what ...,Records & Document Management,meeting_notes
11,Fire,Missing information regarding parcel,Data Management & Visibility,worksheet
12,Fire,Missing information regarding parcel,Data Management & Visibility,worksheet
13,Fire,Inactive parcel that are actually active,Records & Document Management,worksheet
14,Fire,Difficultly for onboarding Searching for parce...,Records & Document Management,meeting_notes
15,Housing Inspectors,Use GIS maps Property lines and getting right ...,System Integration,meeting_notes
16,NBD Data Team,Sub parcels are often unused,Records & Document Management,worksheet
17,NBD Internal,Nob hill – multiple addresses on street – does...,Records & Document Management,meeting_notes
18,NBD Internal,Differences between mailing address and parcel...,Records & Document Management,meeting_notes
19,OCHD,[PERSON] recommends trying Parcel History tab/...,Records & Document Management,meeting_notes
20,OCHD,Run into challenge with corner lots - multiple...,Records & Document Management,meeting_notes
21,OCHD,Workaround - they use map view in Image Mate a...,System Integration,meeting_notes
22,OCHD,Have to look at parcel attribute to see if it'...,Records & Document Management,meeting_notes
23,Office Managers,Missing information: Parcel has owner and PM. ...,Data Management & Visibility,meeting_notes
24,Office Managers,Parcel addresses – assessment overwrite is not...,Records & Document Management,meeting_notes
25,Office Managers,If address has a range e.g. 209-12 Milton – if...,Records & Document Management,meeting_notes
26,Permits,Future system to retain – hard to search when ...,Records & Document Management,meeting_notes
27,Permits,Parcel information – on commercial standpoint ...,Records & Document Management,meeting_notes
28,Supervisors,Parcel information not being in one central lo...,Data Management & Visibility,worksheet
29,Supervisors,New garage Resubdivided – looking at new resub...,Records & Document Management,meeting_notes
30,Supervisors,Legal basis for CE process – parcel based,Workflow & Business Processes,meeting_notes
31,Supervisors,Parcel can't see everything under it,Records & Document Management,meeting_notes
32,Zoning,Parcel based but not system of record tracking...,Records & Document Management,worksheet
33,Zoning,History on “inactive parcels”,Records & Document Management,worksheet
34,Zoning,Parcels broken into multiple pieces / units,Records & Document Management,worksheet
35,Zoning,Parcel history search,Records & Document Management,worksheet
36,Zoning,Inactive parcel search option is nice – would ...,Records & Document Management,meeting_notes
37,Zoning,People will say name of unit – mailing address...,Communication & Collaboration,meeting_notes
38,Zoning,No comprehensive system of record up to date w...,Records & Document Management,meeting_notes
39,Zoning,Example: Emerson Ave address – changed to Will...,Records & Document Management,meeting_notes
40,Zoning,Only way to find title address,Records & Document Management,meeting_notes
41,Zoning,Workaround: Type into county GIS map or Camino,System Integration,meeting_notes
42,Assessment,Do sometimes look at real estate listings – ma...,Records & Document Management,meeting_notes
43,BAA ALJs,Need to look up each address,Records & Document Management,worksheet
44,BAA Operations,Draft D&O to mail out – sometimes more than on...,Records & Document Management,meeting_notes
45,Building Inspectors,See high-risk area from IPS parcel area,Records & Document Management,meeting_notes
46,Supervisors,Big apartment comlexes – hard to go thrugh a N...,Case Management,meeting_notes
47,Zoning,"Didn't come up, but also so much in CE related...",Case Management,meeting_notes

### Cluster 17 — nan (16 records)

,focus_group,pain_points,Category,source
0,Admin Aide,With LLCs do have to keep it distinct if multi...,Data Management & Visibility,meeting_notes
1,Admin Aide,Can't find new owners – creates an issue becau...,Communication & Collaboration,meeting_notes
2,BAA ALJs,One owner with multiple properties,Case Management,worksheet
3,BAA ALJs,One property to multiple owner,Case Management,worksheet
4,BAA ALJs,"When ownership changes, prior owner's fines/fe...",Workflow & Business Processes,meeting_notes
5,BAA ALJs,"Multiple owners and same owner re-cited, doubl...",Case Management,meeting_notes
6,BAA ALJs,"When PO owns multiple properties, no way to vi...",Case Management,meeting_notes
7,CPC,If unpaid and sold to new owner – new owner no...,Case Management,meeting_notes
8,CPC,Could pay it and sue civilly – technically new...,Case Management,meeting_notes
9,CPO-Coordinators,Updating owner information,Records & Document Management,worksheet
10,CPO-Coordinators,10 different accounts under same owners -,Case Management,meeting_notes
11,Housing Inspectors,"If address updated, have to individually updat...",Case Management,meeting_notes
12,Housing Inspectors,Ownership changes – switched in some cases whe...,Case Management,meeting_notes
13,Permits,Properties with multiple units and multiple bu...,Records & Document Management,meeting_notes
14,CPC,Any accounts listed under an individual,Records & Document Management,worksheet
15,Zoning,Ownership chenges,Records & Document Management,worksheet

### Cluster 18 — nan (36 records)

,focus_group,pain_points,Category,source
0,Admin Aide,Cannot search person with associated addresses...,Records & Document Management,worksheet
1,Admin Aide,Reverts to former address updated addresses do...,Records & Document Management,worksheet
2,Admin Aide,M: Pixel perfect when searching by address in ...,Records & Document Management,meeting_notes
3,Admin Aide,Updating address only annoying,Records & Document Management,meeting_notes
4,Admin Aide,Sheer amount of duplicates in address book in ...,System Integration,meeting_notes
5,Admin Aide,Put in contact information – enter someone wit...,Data Management & Visibility,meeting_notes
6,Admin Aide,Automatically adds hypens with phone number,Communication & Collaboration,meeting_notes
7,Admin Aide,Can see contact phone numbers,Communication & Collaboration,meeting_notes
8,Admin Aide,That needs to be updated,Training & Documentation,meeting_notes
9,BAA Supervisors,Unreliable address search,Records & Document Management,worksheet
10,Building Inspectors,Updated Contact Information,Communication & Collaboration,worksheet
11,Building Inspectors,Updated address,Records & Document Management,worksheet
12,Building Inspectors,IPS updates itself Multiple owners in Address ...,Case Management,meeting_notes
13,Building Inspectors,Multiple ways to update in system – if not upd...,Workflow & Business Processes,meeting_notes
14,CPO-Coordinators,Saves incorrect search terms like an address s...,Records & Document Management,meeting_notes
15,CPO-Coordinators,Adding new address will be told that contact a...,Records & Document Management,meeting_notes
16,CPO-Coordinators,IPS auto-fills contact information on forms,Data Management & Visibility,meeting_notes
17,Housing Inspectors,Addresses aren't always updated,Records & Document Management,worksheet
18,Housing Inspectors,Addresses not always updated in all the cases,Case Management,meeting_notes
19,NBD Internal,Address look-up – likes that View tab is chron...,User Experience & Performance,meeting_notes
20,NBD Internal,IPS: Contact book is an abyss – system that ca...,System Integration,meeting_notes
21,Office Managers,Address updating – having to click on contact ...,Records & Document Management,worksheet
22,Office Managers,Update addresses in IPS – need to click on con...,Records & Document Management,meeting_notes
23,Office Managers,Would be nice to see previous addresses,Records & Document Management,meeting_notes
24,Office Managers,Address book: can have 15 different options fo...,Records & Document Management,meeting_notes
25,Office Managers,Dislikes Address book can also be flooded with...,Data Management & Visibility,meeting_notes
26,Office Managers,Have to update the lot to make sure everything...,Records & Document Management,meeting_notes
27,Permits,ROW – doesn't move onto an address,Records & Document Management,meeting_notes
28,Supervisors,Inconsistent / lagging contact information,Data Management & Visibility,worksheet
29,Zoning,Address tracking after resub division,Records & Document Management,worksheet
30,Zoning,Gets stuck with finding address in OnBase – on...,Records & Document Management,meeting_notes
31,Zoning,Variables in addressing becomes different,Records & Document Management,meeting_notes
32,Zoning,Won't take hypenated address – OnBase – format...,Records & Document Management,meeting_notes
33,Zoning,OnBase – however it was key – 7 character limi...,System Integration,meeting_notes
34,BAA Operations,Having to search by tax ID instead of address,Records & Document Management,worksheet
35,Supervisors,Can't find under a specific address if it was ...,Records & Document Management,meeting_notes

In [23]:
# add a new column called cluster_number
df["cluster_number"] = df["Cluster"]

# add a new column called cluster_label
df["cluster_label"] = df["Cluster_Label"]

## 6. Visualizations

In [ ]:
category_counts = (
    df.groupby("Category", as_index=False)
    .size()
    .rename(columns={"size": "Count"})
    .sort_values("Count", ascending=True)
)
fig_cat = px.bar(
    category_counts, x="Count", y="Category", orientation="h",
    title="Pain point categories", color="Count", color_continuous_scale="Blues",
)
fig_cat.update_layout(showlegend=False, height=500, template="plotly_white")
fig_cat.show()

expectation_counts = (
    expectations_df.groupby("Category", as_index=False)
    .size()
    .rename(columns={"size": "Count"})
    .sort_values("Count", ascending=True)
)
fig_exp_cat = px.bar(
    expectation_counts, x="Count", y="Category", orientation="h",
    title="Expectation categories", color="Count", color_continuous_scale="Teal",
)
fig_exp_cat.update_layout(showlegend=False, height=500, template="plotly_white")
fig_exp_cat.show()

In [35]:
coords_2d = umap.UMAP(
    n_neighbors=15, n_components=2, min_dist=0.1, metric="cosine", random_state=42
).fit_transform(challenge_embeddings)
plot_df = pd.DataFrame({
    "x": coords_2d[:, 0], "y": coords_2d[:, 1],
    "Category": df["Category"].values,
    "Cluster_Label": df["Cluster_Label"].values,
    "Challenge": df[CHALLENGE_TEXT_COL].values,
    "Focus Group": df["focus_group"].values,
})
fig_map = px.scatter(
    plot_df, x="x", y="y", color="Category",
    hover_data=["Focus Group", "Cluster_Label", "Challenge"],
    title="2D semantic map by category",
)
fig_map.update_layout(height=560, width=1100, template="plotly_white")
fig_map.show()

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

In [33]:
ch_c = df["Category"].value_counts()
ex_c = expectations_df["Category"].value_counts()
cats = sorted(set(ch_c.index) | set(ex_c.index), key=lambda c: -(ch_c.get(c, 0) + ex_c.get(c, 0)))
plot_cmp = pd.DataFrame({
    "Category": cats,
    "Challenges": [int(ch_c.get(c, 0)) for c in cats],
    "Expectations": [int(ex_c.get(c, 0)) for c in cats],
}).melt(id_vars="Category", var_name="Type", value_name="Count")
fig_cmp = px.bar(
    plot_cmp, x="Count", y="Category", color="Type", barmode="group", orientation="h",
    title="Challenges vs expectations by theme",
    color_discrete_map={"Challenges": "#E76F51", "Expectations": "#2A9D8F"},
)
fig_cmp.update_layout(height=520, template="plotly_white", yaxis=dict(categoryorder="total ascending"))
fig_cmp.show()

In [ ]:
top_n = 18
top = df.groupby("focus_group").size().sort_values(ascending=False).head(top_n)
exp = expectations_df.groupby("focus_group").size()
plot_top = pd.DataFrame({
    "Focus Group": top.index.tolist(),
    "Challenges": top.values.astype(int),
    "Expectations": [int(exp.get(g, 0)) for g in top.index],
}).melt(id_vars="Focus Group", var_name="Kind", value_name="Count")
fig_top = px.bar(
    plot_top,
    x="Focus Group",
    y="Count",
    color="Kind",
    barmode="group",
    title=f"Top {top_n} focus groups",
    color_discrete_map={"Challenges": "#E76F51", "Expectations": "#2A9D8F"},
    category_orders={"Focus Group": top.index.tolist()},
)
fig_top.update_layout(
    height=560,
    width=1100,
    template="plotly_white",
    xaxis=dict(tickangle=-40),
    margin=dict(b=140),
)
fig_top.show()

In [31]:
heatmap_df = pd.crosstab(df["focus_group"], df["Category"])
focus_group_order = heatmap_df.sum(axis=1).sort_values(ascending=False).index
category_order = heatmap_df.sum(axis=0).sort_values(ascending=False).index
heatmap_df = heatmap_df.loc[focus_group_order, category_order].T
fig_heatmap = px.imshow(
    heatmap_df,
    labels=dict(x="Focus Group", y="Category", color="Count"),
    # title="Focus group vs category",
    color_continuous_scale="YlOrRd", text_auto=True, aspect="auto",
)
fig_heatmap.update_layout(height=700, width=1100, xaxis_tickangle=-45, template="plotly_white")
fig_heatmap.show()

## 7. Save categorized outputs

In [25]:
challenge_cols = [
    c for c in [
        "department", "focus_group", CHALLENGE_TEXT_COL, "processed_text", "source", "sentiment",
        "title", "Category", "Category_Method", "Category_Confidence",
        "Cluster", "Cluster_Label",
    ] if c in df.columns
]
expectation_cols = [
    c for c in [
        "department", "focus_group", EXPECTATION_TEXT_COL, "processed_text", "source", "sentiment",
        "title", "Category", "Category_Method", "Category_Confidence",
    ] if c in expectations_df.columns
]

df[challenge_cols].to_csv(CATEGORIZED_CHALLENGES_CSV, index=False, encoding="utf-8-sig")
expectations_df[expectation_cols].to_csv(
    CATEGORIZED_EXPECTATIONS_CSV, index=False, encoding="utf-8-sig"
)
category_summary = (
    df.groupby("Category", as_index=False).size()
    .rename(columns={"size": "Count"})
    .sort_values("Count", ascending=False)
)
category_summary.to_csv(CATEGORY_SUMMARY_CSV, index=False, encoding="utf-8-sig")

print(f"Saved {CATEGORIZED_CHALLENGES_CSV} ({len(df)} rows)")
print(f"Saved {CATEGORIZED_EXPECTATIONS_CSV} ({len(expectations_df)} rows)")
print(f"Saved {CATEGORY_SUMMARY_CSV}")
display(category_summary)

Saved output/processed/categorized_challenges.csv (937 rows)
Saved output/processed/categorized_expectations.csv (548 rows)
Saved output/processed/category_summary.csv

                           Category  Count
3     Records & Document Management    207
0                   Case Management    199
6                System Integration    126
8     User Experience & Performance     93
1     Communication & Collaboration     88
9     Workflow & Business Processes     76
5  Scheduling & Resource Management     60
2      Data Management & Visibility     51
7          Training & Documentation     21
4      Reporting & Decision Support     16