In [1]:
%pip install -r ../requirements.txt

Requirement already satisfied: transformers in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from -r ../requirements.txt (line 1)) (5.12.1)
Requirement already satisfied: torch in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from -r ../requirements.txt (line 2)) (2.12.1)
Requirement already satisfied: tqdm in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from -r ../requirements.txt (line 3)) (4.68.3)
Requirement already satisfied: python-dotenv in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from -r ../requirements.txt (line 4)) (1.2.2)
Requirement already satisfied: pandas in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from -r ../requirements.txt (line 6)) (3.0.3)
Requirement already satisfied: numpy in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from -r ../requirements.txt (line 7)) (2.4.6)
Requirement already satisfied: matplotlib in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from -r ../requirements.txt (line 8)) (3.10.9)
Requirement already satisfied: wordcloud in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from -r ../requirements.txt (line 9)) (1.9.6)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from transformers->-r ../requirements.txt (line 1)) (1.21.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\sbhalerao\AppData\Roaming\Python\Python314\site-packages (from transformers->-r ../requirements.txt (line 1)) (26.2)
Requirement already satisfied: pyyaml>=5.1 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from transformers->-r ../requirements.txt (line 1)) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from transformers->-r ../requirements.txt (line 1)) (2026.6.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from transformers->-r ../requirements.txt (line 1)) (0.22.2)
Requirement already satisfied: typer in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from transformers->-r ../requirements.txt (line 1)) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from transformers->-r ../requirements.txt (line 1)) (0.8.0)
Requirement already satisfied: click>=8.4.0 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->-r ../requirements.txt (line 1)) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->-r ../requirements.txt (line 1)) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->-r ../requirements.txt (line 1)) (2026.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->-r ../requirements.txt (line 1)) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->-r ../requirements.txt (line 1)) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers->-r ../requirements.txt (line 1)) (4.15.0)
Requirement already satisfied: anyio in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->-r ../requirements.txt (line 1)) (4.14.1)
Requirement already satisfied: certifi in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->-r ../requirements.txt (line 1)) (2026.6.17)
Requirement already satisfied: httpcore==1.* in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->-r ../requirements.txt (line 1)) (1.0.9)
Requirement already satisfied: idna in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->-r ../requirements.txt (line 1)) (3.18)
Requirement already satisfied: h11>=0.16 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers->-r ../requirements.txt (line 1)) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from typer->transformers->-r ../requirements.txt (line 1)) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from typer->transformers->-r ../requirements.txt (line 1)) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from typer->transformers->-r ../requirements.txt (line 1)) (0.0.4)
Requirement already satisfied: setuptools<82 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from torch->-r ../requirements.txt (line 2)) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from torch->-r ../requirements.txt (line 2)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from torch->-r ../requirements.txt (line 2)) (3.6.1)
Requirement already satisfied: jinja2 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from torch->-r ../requirements.txt (line 2)) (3.1.6)
Requirement already satisfied: colorama in C:\Users\sbhalerao\AppData\Roaming\Python\Python314\site-packages (from tqdm->-r ../requirements.txt (line 3)) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\sbhalerao\AppData\Roaming\Python\Python314\site-packages (from pandas->-r ../requirements.txt (line 6)) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas->-r ../requirements.txt (line 6)) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->-r ../requirements.txt (line 8)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->-r ../requirements.txt (line 8)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->-r ../requirements.txt (line 8)) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->-r ../requirements.txt (line 8)) (1.5.0)
Requirement already satisfied: pillow>=8 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->-r ../requirements.txt (line 8)) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->-r ../requirements.txt (line 8)) (3.3.2)
Requirement already satisfied: six>=1.5 in C:\Users\sbhalerao\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas->-r ../requirements.txt (line 6)) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from rich>=13.8.0->typer->transformers->-r ../requirements.txt (line 1)) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\sbhalerao\AppData\Roaming\Python\Python314\site-packages (from rich>=13.8.0->typer->transformers->-r ../requirements.txt (line 1)) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers->-r ../requirements.txt (line 1)) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sympy>=1.13.3->torch->-r ../requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\sbhalerao\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jinja2->torch->-r ../requirements.txt (line 2)) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [70]:
from docx import Document
import os
import numpy as np
import pandas as pd

In [75]:
raw_notes = Document('../data/notes.docx')

In [76]:
def split_the_document(doc):
    """
    Splits the document into sections based on Heading 3 paragraphs.
    Returns a list of tuples (heading, content).
    """
    sections = []
    current_heading = None
    current_content = []

    for paragraph in doc.paragraphs:
        paragraph_text = paragraph.text.strip()

        if paragraph.style.name.startswith('Heading 3'):
            if current_heading is not None:
                sections.append((current_heading, '\n'.join(current_content).strip()))
            current_heading = paragraph_text
            current_content = []
        elif current_heading is not None and paragraph_text:
            current_content.append(paragraph_text)

    if current_heading is not None:
        sections.append((current_heading, '\n'.join(current_content).strip()))

    return sections


sections = split_the_document(raw_notes)

In [77]:
print("Sections extracted from the document:")
for heading, content in sections:
    print(f"Heading: {heading}")
    print(f"Content: {content[:100]}...")  # Print first 100 characters of content
    print("-" * 40)

Sections extracted from the document:
Heading: 7DOCE Discovery Session | Admin Aides Group 1
Content: Wed May 20, 2026 | 10-11am
Introductions and Project Background | 5min | Rose
Jordan – Office Manage...
----------------------------------------
Heading: DOCE Discovery Session | Building Inspectors Group 1
Content: Thurs May 21 | 8:30-9:30am
Ashlie Fifield, Dan Marobella, Rob Melcher, Reggie Packer
Introductions
R...
----------------------------------------
Heading: DOCE Discovery Session | Admin Aides Group 2
Content: Thurs May 21 | 10-11am
Eric Osei-Afriyie, Lillian Pagan, Katelynn Campbell
Introductions
Eric, Admin...
----------------------------------------
Heading: DOCE Discovery Session | Supervisors Group
Content: Thurs May 21 | 11am-12pm
Noah Lanning, Bill McCann, Brian Eisenberg, Jake Dishaw, Tom Steinberg, Rya...
----------------------------------------
Heading: DOCE Discovery Session | Housing Inspectors Group
Content: Tues May 26, 2026 | 8:30-9:30am
Kevin Brown, Daniel Frisina, Don Lovejoy, Matthew Moran
Introduction...
----------------------------------------
Heading: DOCE Discovery Session | Commercial/Permit/Electrical Inspectors Group
Content: Fri May 29, 2026 | 8:30-9:30am
Patrick Caples, Daniel Michaels, Terry Madore, Kevin McInerney, John ...
----------------------------------------
Heading: DOCE Discovery Session | Fire Prevention Bureau
Content: Mon Jun 1, 2026 | 12-1pm
Attendees: Chief Cowburn, Kelly Willcox, Brian Fogarty
Introductions
Brian ...
----------------------------------------
Heading: DOCE Discovery Session | Central Permit Office
Content: Mon Jun 1, 2026 | 1-2pm
Attendees: Bob Moore, Teri Bliss, Chad Beckford
(Not available: Jess Brandt,...
----------------------------------------
Heading: DOCE Discovery Session | Zoning
Content: Wed Jun 3, 2026 | 11am-12pm
Participants: Jake Dishaw, Noah Garcia, Nate Pan, Rebeca Baker, Masihull...
----------------------------------------
Heading: DOCE Discovery Session | DOCE Office Staff
Content: Thurs Jun 4, 2026 | 9am-10am
Participants: Timothy O'Connor, Katelynn Campbell
Introductions:
TIm: S...
----------------------------------------
Heading: DOCE Discovery Session | CPO Coordinators
Content: Monday Jun 8, 2026 | 2:30-3:30pm
Participants: Anthony Marmolejos, Maria Johnson, Corinne Hubbard
In...
----------------------------------------
Heading: Discovery Session | Law
Content: Wed June 17, 2026 | 11-12pmn
Attendees: Todd Long, Robert Carpenter, Zachary Waksman, John Connor, T...
----------------------------------------
Heading: Discovery Session | Assessment
Content: Tue June 23, 2026 | 11-12pm
Attendees: , Ann Gallagher, Joseph Lesnau
Unavailable: Matthew Oja
Intro...
----------------------------------------
Heading: BAA Discovery Session | BAA
Content: Tues June 23, 2026 | 3:30-4:40pm
Attendees: Leah Witmer, Cecelia Wallace, Kenneth Jamison (admin aid...
----------------------------------------
Heading: NBD Discovery Session | NBD
Content: Mon June 29, 2026 | 11:00-12:00pm
Attendees: Michelle Sczpanski, Cimone Jordan, Manila Southmmavong,...
----------------------------------------
Heading: CPC Discovery Session | CPC
Content: Mon June 29, 2026 | 3:30-4:30pm
Attendees: Viki Voss, Vincent Nguyen, Daniel Streeter
Role
Vincent -...
----------------------------------------
Heading: NBD Discovery Session | NBD Data Team
Content: Wed Jul 01, 2026 | 9:30-10:30pm
Attendees: Rose, Caleb, Jonah
Role:
Experience:
Rose: 2022
Caleb:
Jo...
----------------------------------------

In [78]:
import pandas as pd

# Keep the section-level table separate from later export tables.
df_sections = pd.DataFrame(sections, columns=['Heading', 'Content'])

def record_mapping_for_each_focus_group(df):
    mapping = {}
    for _, row in df.iterrows():
        heading = row['Heading']
        content_lines = [line.strip() for line in row['Content'].split('\n') if line.strip()]
        if heading not in mapping:
            mapping[heading] = []
        mapping[heading].extend(content_lines)
    return mapping

In [79]:
import json

record_mapping = record_mapping_for_each_focus_group(df_sections)
print(json.dumps(record_mapping, indent=2, ensure_ascii=False))

{
  "7DOCE Discovery Session | Admin Aides Group 1": [
    "Wed May 20, 2026 | 10-11am",
    "Introductions and Project Background | 5min | Rose",
    "Jordan – Office Manager, 5mos",
    "Mastajah – Admin Aides, 6mos (ma-sta-jah)",
    "Shawna – Admin Aide, 1.5yr",
    "Worksheet | 15min | Swapnil",
    "Share Out* | 40 min | Swapnil facilitates, Rose takes notes",
    "Role – general role and main responsibilities",
    "Phone calls from the public – complaint line, or generalized question line, scan documents – rent holds/rentl releases, t&d, n&m ticjkets",
    "Letters folding",
    "Help at the window, people who in come person",
    "Jordan: Help pick up projects",
    "Day to day – writing tickets, send",
    "Ownership verification",
    "Rental Registry maintenance",
    "Shawna: Take complaints, schedule inspections – get a lot of the werid calls, lots of fact finding",
    "Mastajah does most of the nail and mails, Shawna does the phones",
    "Data entry – stuff from Law, stuff from tickets",
    "Process",
    "M: People who call, can also be person who come in person",
    "Inspectors go to first",
    "Most calls – inspector to go out for a complaint",
    "Lots of people want to talk to supervisor",
    "Ask each other questions",
    "Tools: IPS, Camino, catchment map, Outlook, phones",
    "Collaboration tools – all set near each other, most",
    "J: Sends a lot of emails, mostly to inspectors, then BAA tickets",
    "Doesn’t use the phone very much",
    "Day-to-day collab with BAA and internal CE",
    "Email with Permits sometimes not often",
    "Tools: Outlook, IPS, maps, use County Clerk database, uses AS400 for Rental Registry for water billing",
    "S: Does the most – takes phone calls, complaints, schedule inspections",
    "Inspector involved at some point",
    "Speaks with Tom or Bill if there’s an issue – if someone is out, needs another inspector",
    "Tools: IPS, Outlook, GIS, catchment map, Teams, AS400",
    "Rent Holds and Rent Releases – get in contact with NBD – 3 receives them and someone from DSS (Lisbeth Nobel)",
    "Pain points and challenges",
    "M: Unhandled exception error – entered complaint case and crashes",
    "IPS crash 2-3 times per day",
    "S: Scheduling",
    "When person supposed to be in a certain error",
    "Not all explciitly told at the same time who is doing what e.. Pat C. commercial electrical and building insp supposed to be doing what Pat was doing, but no one aware",
    "Periodic Insp module for Rental Registry – annoying, unorganized",
    "Inspector names not alphabetized",
    "Scheduling appoiintment – that is alphabetized",
    "Inspection schedule and inspection note",
    "Only use 2 out of the 20 options – actions in the drop-down in the periodics module",
    "Default options in complaint module always pre-populated – would be helpful for it to autofill",
    "Each appointment – have to schedule in 2-3 places (Outlooks, Periodics module) - if all calendars could be auto-filled that would be helpful",
    "CofU or CofI – would be nice if all inspectors could collaborate on it, rather than setting up individually",
    "Bldg, Fire, Electrical – schedule each individually",
    "Our phones are on a time limit – 5min max – drops automatically – IT has known about this issue – people call back and yell because they think they hung up",
    "4-5 properties scheduling inspections for – call will drop bc time consuming to schedule each one",
    "20 calls dropped between 4 of them one week",
    "20min wasted time due to phones",
    "J: IPS crashing",
    "Loud sighs",
    "BAA ticketing – processes seem inconsist and stupid – BAA would send back a ticket with a minor correction i.e. period off or missing letter ‘t’ Scott",
    "Find ticket – make a single character edit",
    "They could edit it on their end",
    "Problem bc inspector should sign, then inspector could edit it – delay by days",
    "BAA inconsistent – send back tickets for taking out a care/of line or making it a second line or saying Image Mate has 2 people listed but  – but only cited one person",
    "Address for owner legit address – deed search and on Image Mate, who we sent violation notice to",
    "BAA tried to send to PO Box – didn't go through – couldn't serve it twice, denied ticket and sent it back",
    "His work around – said Law verify address",
    "S: Limit on tabs IPS can handle- multi-task – may have 7 tabs open, upload documents, tabs open – when that error comes up – is there a limit to tabs before crashes? On average ~10 complaint cases open",
    "Managing multiple tools – is that frustrating? Could be a more efficient way to have all the things they use. Shawn: very analog so doesn’t know what that would look like GIS map",
    "Deed search – if inspectors listed with parcel info",
    "Would save time if all info on catchment map were in IPS on the parcel – but still wouldn’t have geographic context",
    "M: Pixel perfect when searching by address in AS400 – very difficult, functionality atrocious, like the aesthetic",
    "J: AS400 – uses it for water billing, goes to view wtr history and won’t go anywhere – will go ‘long way’ - additional 3 steps – even then sometimes it’s not there",
    "Only more annoying because",
    "Kevin gave long list of address changes – updating owner addresses in AS400 and in IPS",
    "Updating address only annoying",
    "Death certificate 2003 of someone trying to serve",
    "Can they have assessment update the address?",
    "IPS doesn’t allow saving owner addresses sometimes – or permission based? Tim could do it",
    "Sheer amount of duplicates in address book in IPS and AS400 – some of that is the owner addresses themselves",
    "With LLCs do have to keep it distinct if multiple LLCs so not all within our control",
    "Put in contact information – enter someone with same name, address book won’t let you enter it if it’s similar – e.g. enter same name but different address",
    "Assessment change of address form – share",
    "Anything you like about IPS",
    "Automatically adds hypens with phone number",
    "Appreciates that within parcel, can click on button that brings directly to Image Mate with the owner address",
    "Dark mode for IPS?  +2 Incredibly bright",
    "Other information you wish were available or features/capabailities?",
    "Spell check or grammar check",
    "Not consistent – some parts have features and others don’t",
    "If everything could be more easily identifiable on the thumbnails – when you pull ip the Parcel History, not easy to tell e..g large complexes like Nob Hill, has to open each individually to find apartment – make it more identifiable e.g. apartment, unit – only has status, open date",
    "Finding/opening specific cases difficult",
    "Computer is slow – takes 45 sec to open complaint case",
    "When you open a case note on an already open case – sometimes your name isn’t there – blank space – sometimes only inspectors are there",
    "Some things you need to hit Save and other time you don’t need to",
    "Save button never in the same place or",
    "New next to Save and look the same",
    "Notepads, a lot of Excel documents",
    "S: Doesn’t use Excel on day to day",
    "Made cheat sheets and phone lists of commonly ysed things – reference docs",
    "Deed search, GIS,",
    "MS Teams: will contact cityline Christine Norween",
    "Inspectors update SeeClick Fix – not admin aides",
    "Mondays are the busiest – 9 or 3pm",
    "Closing/Next Steps | 5min | Rose"
  ],
  "DOCE Discovery Session | Building Inspectors Group 1": [
    "Thurs May 21 | 8:30-9:30am",
    "Ashlie Fifield, Dan Marobella, Rob Melcher, Reggie Packer",
    "Introductions",
    "Rob Melcher: Housing > Building - 5yrs",
    "Ashlie: Clerk > Admin Supervisor > Housing > Building - 20yrs",
    "Dan: Housing > Building – 2018 (8 yrs)",
    "Reggie: Housing > Building (4 yrs) - 2019 (7 yrs)",
    "Luke: Vacants (separate dept at the time, just him and Ryan) - 23yrs",
    "Share Out",
    "Role",
    "Building inspecor: CofC, CofU, Zoning, permits, tobacco, CofA, CofI, permit inspections – floaters for now if they’re booked up",
    "Gave it to certain inspectors",
    "Process",
    "Intake/scheduling",
    "Depends on the inspection",
    "CofU – Corinne gets applications and she schedules",
    "CofC – Anthony and Maria – application side – call and schedule (doesn’t always happen)",
    "May be due for CofC before app even comes up, and inspector will start",
    "CofU/CofI – Fire and electrical",
    "Sometimes Fire does their own thing",
    "Aides schedule CofU – can be diconnect between Fire and inspector going",
    "Outlook, IPS, Outlook calendar – doesn't even",
    "Inspections",
    "Electrical test, camera in iPhone for photos",
    "Got tablets years ago – great idea, too much lag – heard that IT didn’t want to pay for updates on tablets",
    "Restricts them in the field - don't know what’s cited",
    "Reggie’s tablet does work – needs hotspots to work",
    "Photos go right into case – notes go in straighaway",
    "IPhones were great when they got them",
    "IPads with IPS app are droid companability – doesn't work with iPhones",
    "Taking notes on paper and picture on phone",
    "Before go out – checking out what’s required, whether they need dust wipes (lead)",
    "Back in the office – type up notes",
    "End of the day – depends on number of cases and violations",
    "Doing it in the field would save a ton of time",
    "Send themsevles",
    "Got them new tablets – first day doesn’t work",
    "Case management",
    "Daily workload and total workload",
    "You set up your own tickle date – not automated",
    "You have red to know if you’re really behind",
    "If you forgot to put tickle date in – cases are lost",
    "IPS crashes – 3 or 4 cases – someone calls – may have lost your case – doesn't save session",
    "BAA process",
    "In an area where people get scared with the notices",
    "Rollover – if taxes unpaid, can’t get CofC",
    "Not supposed to issue cert with taxes – can issue if in tax trust",
    "PO lie all the time – Assmt",
    "Different info from different departments",
    "Can’t send PO to BAA if tax delinquent per – if only thing is CofC being held up",
    "Pain Points & Challenges",
    "Rob: Zoning approval – Zone checks take forever – he knows they’re very busy",
    "Can’t issue without zone check, they don’t update IPS case",
    "Other depts that get involved – don't update IPS with notes, can be an issue",
    "Inspectors are point of contact – get people calling – waiting for BAA, Law or Zoning",
    "Nob Hill – cited over 2 years ago for elevators – due in 2019",
    "Ashlie - she didn’t know they were – can't cite if don’t know it’s expired",
    "Referred to Law in May 2024",
    "DOCE get blamed a lot",
    "2 years since it’s been referred to Law and no note from Law",
    "Inspectors aren’t updated with info when cases are in court even some times – gets info from syracuse.com",
    "Third-party inspectors: Sprinklers, fire alarm, smoke certs if hardwired, boilers/furnace, HVAC, elevators",
    "Will put reports to fire marshal and they will review and approve",
    "Only a few have access to Compliance Engine to look it up",
    "Water check – gets another inspector to look up the water movement",
    "Difficult for AS400 to use",
    "Technology",
    "See the water and elevator certs – have to ask Sonya – no note if it’s passed or paid",
    "i.e. Can’t finish the CofC application until that’s in",
    "Tools – Camino for permits",
    "Can read notes from owners",
    "Mainly checking if doing work without a permit",
    "Also where applications come in for CofCs",
    "May check on whether they’re pulling permits, whether its passed",
    "Wait on zoning again",
    "Approvals for CofUs – redtape owners need to go through – slows down the process – DPW, zoning, Law, police",
    "IPS – likes",
    "Tickle dates – reminder dates are helpful",
    "Too many cases that they manage",
    "Ashlie – liked AS400 – had everything in there",
    "Now hopping back and forth",
    "Likes that all documents and images are saved in there – even communication with owner",
    "With BAA, have to provide pictures",
    "Photos also helpful for inspectors – compare/contrast",
    "Options for actions in IPS – everything all in there",
    "If you’re interrupted",
    "AS400 you can look up missed assignments",
    "Couldn’t save documents in there – had to go into Onbase",
    "Likes it for certain things, doesn’t like it for others",
    "Ashlie started as paralegal – between Codes and Law – also a clerk – started with RR program – easier for her, can look anything up",
    "IPS – can search for anything",
    "Issue for clerks as well – Nob Hill eg. Huge list of cases – issue with searching – sift through all of those cases",
    "Anthony – add CofC case apps, gets added to older cases",
    "DPW had their own cases in IPS when they first started – older cases",
    "Fire will also start their own cases in IPS – they don’t follow up on it – now inspectors do it for them",
    "County lead in there too – can see it – but makes more cases",
    "IPS – ownership issues",
    "IPS updates itself",
    "Multiple owners in Address Book – has to go in as multiple entries even if the same individual",
    "Reggie’s case changed – he tries to change the older – causes confusion, multiple listed",
    "If you try to delete causes issues",
    "BAS said nothing they can do about it",
    "So many places something can be put in – which ones is the correct updated ownership, phone numbers, etc. - and which was last put in is not indicated",
    "Multiple ways to update in system – if not updated in certain way, doesn’t get",
    "AS400 checks 4 way – Ashlie uses constantly, Rob not familiar with it",
    "Used to be trained on it day one",
    "Don’t use spreadsheets – but supervisors do",
    "Tracking",
    "Features or capabilities you wish IPS had",
    "When it crashes – if it could refresh with where you are",
    "Happens often – too many windows open",
    "Letters admin aides think it’s an issue– if doing same thing at the same time",
    "Same property – multiple cases",
    "See high-risk area from IPS parcel area",
    "Catchment map",
    "Be nice if IPS had everything they needed – now we have so many apps",
    "Sonya elevators, catchment map, Camino, Compliance Engine",
    "Tablet that connects – idea is great",
    "Ashlie had skyline at the time – 45 minutes to pull up cases",
    "More info cases in IPS harder it would be to",
    "Offline capability – if they go into a basement to look at boiler, service drops/tablet wouldn’t work",
    "Would be interesting to see what other municipalities use for software – in NYS same codes",
    "Ashlie has high hopes – this meeting longer already than the one they held when picking IPS (Gretchen in Law? At the time)",
    "Luke: Codes wasn’t consulted",
    "Items Dan M. followed up with via email 2026-05-26:",
    "Some of the inspectors do not have the ability to delete actions or photos in IPS if they are added by mistake. A lot of them come to me to do that for them.",
    "Several inspectors do not have access to AS400. We do need this to check for proper ownership as well as water usage to determine vacancy."
  ],
  "DOCE Discovery Session | Admin Aides Group 2": [
    "Thurs May 21 | 10-11am",
    "Eric Osei-Afriyie, Lillian Pagan, Katelynn Campbell",
    "Introductions",
    "Eric, Admin Aide, 2024",
    "Lillian, Admin Aide, 2024",
    "Share Out",
    "Role",
    "Mostly make calls, schedule complaints, schedule inspections – bulk of what they do",
    "Grab things from the printer – mailings from printer",
    "Rent holds and rent releases – occur every day – not all working on all at the same time",
    "Lillian: Point of contact – general public that comes in – her or Maria handle the spanish speaking population and handle inspections for them upstairs (if Maria not there may help out downstairs or Suehaly or Jenifer from SPD)",
    "Speak to inspectors, or Land Bank or zoning plans examiners",
    "Gets overwhelming – just one window",
    "Someone calls trying to schedule inspection or PO wants information – just one window – gets congested",
    "People showing up a lot and calling a lot",
    "Handling voicemails and callbacks",
    "Issues with phones – started 2-3 months – phone calls just drop – people frustrated because phone drops – IT tickets on it since 2024",
    "They don’t just get CE phone calls – field calls for multiple departments – get calls for cityline or DPW – get a lot of phone traffic",
    "Try to direct them to departments – those departments don’t pick up the phone – try to give them an alternative solution i.e. fill out form",
    "Website – tried to create a ticket through seeclickfix – got a blank screen*",
    "Tools",
    "IPS, phones, Caminos",
    "Camino is the smoothest – up-to-date, reliable – runs well compared to everything else",
    "Sometimes don’t upload the inspectors",
    "AS400 – water notes, update ownership records, taxes",
    "Katelyn uses it the most",
    "Don’t track things mostly outside of IPS",
    "Outlook",
    "Tim monitors main codes email",
    "Will send copies of things through their emails – send a lot of attachments",
    "They use spreadsheets scarcily – only one recently",
    "Collaboration with other depts",
    "Use Teams or use phone extensions",
    "Document a lot in IPS just to make sure it’s there",
    "If in the office, visit in person",
    "Process",
    "Pain Points & Challenges",
    "Would be nice for a section specifically for Law/legal",
    "7D court filings – don't have a dedicated place for this – would be nice if legal had their own section for it. If no case, adding to other general attachments – a lot in there – their own designated space for it to be uploaded",
    "IPS: when trying to save anything – brink of crashing – slows down – loading window – if crashes, will say out of memory",
    "Periodic inspections module: Issue with inspector names not sorting alphabetize",
    "Everything else runs pretty smoothly – mainly processing speed",
    "If updating nail and mails – sometimes you can’t upload the document",
    "Issue with feature – put in a complaint under building without a permit – when it times to send out letter *follow up with Tim for details",
    "Mainly put under Prop Maint Int/Ext - would be more recognizable as Bldg w/o a Permit",
    "Katelyn creates tickets",
    "Re: mailing a letter out - Sometimes can’t find the new owner in the system – go into county clerk’s deeds and mortgages",
    "Can’t find new owners – creates an issue because old owners calls us, become aggravated/agitated because they sold it",
    "Collaboration with other departments?",
    "When waiting on approval for something – if they can’t get ahold of Permits office",
    "Eric: Likes that everything is in Camino – database for that",
    "Multiple tools they have to handle – would be nice if something that collected those data and inputted in both systems",
    "AS400: Do use it often, very outdated",
    "Lillian not really trained on AS400",
    "Technology",
    "Features you like/that work well",
    "Likes periodics window for Rental Registry",
    "Documents on one side, inspection on the other side, add notes to it specifically",
    "PI module layout – likes it better than the complaint module – designed well – when you click on date, doesn’t calendar – very useful",
    "Likes the layout",
    "Only complaint is the list alphabetize",
    "Can see contact phone numbers",
    "That needs to be updated",
    "Owner/contact information – needs to be connected – updated individually in RR module vs complaint module",
    "Attachment for CofUs – don't see it in the attachments",

In [83]:
#get first two values from list of the keys in the record_mapping dictionary
first_two_values = {key: value[:2] for key, value in record_mapping.items()}
print(json.dumps(first_two_values, indent=2, ensure_ascii=False))

{
  "7DOCE Discovery Session | Admin Aides Group 1": [
    "Wed May 20, 2026 | 10-11am",
    "Introductions and Project Background | 5min | Rose"
  ],
  "DOCE Discovery Session | Building Inspectors Group 1": [
    "Thurs May 21 | 8:30-9:30am",
    "Ashlie Fifield, Dan Marobella, Rob Melcher, Reggie Packer"
  ],
  "DOCE Discovery Session | Admin Aides Group 2": [
    "Thurs May 21 | 10-11am",
    "Eric Osei-Afriyie, Lillian Pagan, Katelynn Campbell"
  ],
  "DOCE Discovery Session | Supervisors Group": [
    "Thurs May 21 | 11am-12pm",
    "Noah Lanning, Bill McCann, Brian Eisenberg, Jake Dishaw, Tom Steinberg, Ryan Shiel, Mujahid Muhammad"
  ],
  "DOCE Discovery Session | Housing Inspectors Group": [
    "Tues May 26, 2026 | 8:30-9:30am",
    "Kevin Brown, Daniel Frisina, Don Lovejoy, Matthew Moran"
  ],
  "DOCE Discovery Session | Commercial/Permit/Electrical Inspectors Group": [
    "Fri May 29, 2026 | 8:30-9:30am",
    "Patrick Caples, Daniel Michaels, Terry Madore, Kevin McInerney, John McMahon, Thomas O'Mara"
  ],
  "DOCE Discovery Session | Fire Prevention Bureau": [
    "Mon Jun 1, 2026 | 12-1pm",
    "Attendees: Chief Cowburn, Kelly Willcox, Brian Fogarty"
  ],
  "DOCE Discovery Session | Central Permit Office": [
    "Mon Jun 1, 2026 | 1-2pm",
    "Attendees: Bob Moore, Teri Bliss, Chad Beckford"
  ],
  "DOCE Discovery Session | Zoning": [
    "Wed Jun 3, 2026 | 11am-12pm",
    "Participants: Jake Dishaw, Noah Garcia, Nate Pan, Rebeca Baker, Masihullah Omary, Sam Prescott, Suzuki, Hillary"
  ],
  "DOCE Discovery Session | DOCE Office Staff": [
    "Thurs Jun 4, 2026 | 9am-10am",
    "Participants: Timothy O'Connor, Katelynn Campbell"
  ],
  "DOCE Discovery Session | CPO Coordinators": [
    "Monday Jun 8, 2026 | 2:30-3:30pm",
    "Participants: Anthony Marmolejos, Maria Johnson, Corinne Hubbard"
  ],
  "Discovery Session | Law": [
    "Wed June 17, 2026 | 11-12pmn",
    "Attendees: Todd Long, Robert Carpenter, Zachary Waksman, John Connor, Toryana Jackson"
  ],
  "Discovery Session | Assessment": [
    "Tue June 23, 2026 | 11-12pm",
    "Attendees: , Ann Gallagher, Joseph Lesnau"
  ],
  "BAA Discovery Session | BAA": [
    "Tues June 23, 2026 | 3:30-4:40pm",
    "Attendees: Leah Witmer, Cecelia Wallace, Kenneth Jamison (admin aide), Tashonia Carter (supervisor - PVB)"
  ],
  "NBD Discovery Session | NBD": [
    "Mon June 29, 2026 | 11:00-12:00pm",
    "Attendees: Michelle Sczpanski, Cimone Jordan, Manila Southmmavong, Patty Lynch, Adol Mayen, Madison Young, Kaylin Hubbard"
  ],
  "CPC Discovery Session | CPC": [
    "Mon June 29, 2026 | 3:30-4:30pm",
    "Attendees: Viki Voss, Vincent Nguyen, Daniel Streeter"
  ],
  "NBD Discovery Session | NBD Data Team": [
    "Wed Jul 01, 2026 | 9:30-10:30pm",
    "Attendees: Rose, Caleb, Jonah"
  ]
}

In [86]:
#drop the first two values from the list of the keys in the record_mapping dictionary
records = {key: value[2:] for key, value in record_mapping.items()}
print(json.dumps(records, indent=2, ensure_ascii=False))

{
  "7DOCE Discovery Session | Admin Aides Group 1": [
    "Jordan – Office Manager, 5mos",
    "Mastajah – Admin Aides, 6mos (ma-sta-jah)",
    "Shawna – Admin Aide, 1.5yr",
    "Worksheet | 15min | Swapnil",
    "Share Out* | 40 min | Swapnil facilitates, Rose takes notes",
    "Role – general role and main responsibilities",
    "Phone calls from the public – complaint line, or generalized question line, scan documents – rent holds/rentl releases, t&d, n&m ticjkets",
    "Letters folding",
    "Help at the window, people who in come person",
    "Jordan: Help pick up projects",
    "Day to day – writing tickets, send",
    "Ownership verification",
    "Rental Registry maintenance",
    "Shawna: Take complaints, schedule inspections – get a lot of the werid calls, lots of fact finding",
    "Mastajah does most of the nail and mails, Shawna does the phones",
    "Data entry – stuff from Law, stuff from tickets",
    "Process",
    "M: People who call, can also be person who come in person",
    "Inspectors go to first",
    "Most calls – inspector to go out for a complaint",
    "Lots of people want to talk to supervisor",
    "Ask each other questions",
    "Tools: IPS, Camino, catchment map, Outlook, phones",
    "Collaboration tools – all set near each other, most",
    "J: Sends a lot of emails, mostly to inspectors, then BAA tickets",
    "Doesn’t use the phone very much",
    "Day-to-day collab with BAA and internal CE",
    "Email with Permits sometimes not often",
    "Tools: Outlook, IPS, maps, use County Clerk database, uses AS400 for Rental Registry for water billing",
    "S: Does the most – takes phone calls, complaints, schedule inspections",
    "Inspector involved at some point",
    "Speaks with Tom or Bill if there’s an issue – if someone is out, needs another inspector",
    "Tools: IPS, Outlook, GIS, catchment map, Teams, AS400",
    "Rent Holds and Rent Releases – get in contact with NBD – 3 receives them and someone from DSS (Lisbeth Nobel)",
    "Pain points and challenges",
    "M: Unhandled exception error – entered complaint case and crashes",
    "IPS crash 2-3 times per day",
    "S: Scheduling",
    "When person supposed to be in a certain error",
    "Not all explciitly told at the same time who is doing what e.. Pat C. commercial electrical and building insp supposed to be doing what Pat was doing, but no one aware",
    "Periodic Insp module for Rental Registry – annoying, unorganized",
    "Inspector names not alphabetized",
    "Scheduling appoiintment – that is alphabetized",
    "Inspection schedule and inspection note",
    "Only use 2 out of the 20 options – actions in the drop-down in the periodics module",
    "Default options in complaint module always pre-populated – would be helpful for it to autofill",
    "Each appointment – have to schedule in 2-3 places (Outlooks, Periodics module) - if all calendars could be auto-filled that would be helpful",
    "CofU or CofI – would be nice if all inspectors could collaborate on it, rather than setting up individually",
    "Bldg, Fire, Electrical – schedule each individually",
    "Our phones are on a time limit – 5min max – drops automatically – IT has known about this issue – people call back and yell because they think they hung up",
    "4-5 properties scheduling inspections for – call will drop bc time consuming to schedule each one",
    "20 calls dropped between 4 of them one week",
    "20min wasted time due to phones",
    "J: IPS crashing",
    "Loud sighs",
    "BAA ticketing – processes seem inconsist and stupid – BAA would send back a ticket with a minor correction i.e. period off or missing letter ‘t’ Scott",
    "Find ticket – make a single character edit",
    "They could edit it on their end",
    "Problem bc inspector should sign, then inspector could edit it – delay by days",
    "BAA inconsistent – send back tickets for taking out a care/of line or making it a second line or saying Image Mate has 2 people listed but  – but only cited one person",
    "Address for owner legit address – deed search and on Image Mate, who we sent violation notice to",
    "BAA tried to send to PO Box – didn't go through – couldn't serve it twice, denied ticket and sent it back",
    "His work around – said Law verify address",
    "S: Limit on tabs IPS can handle- multi-task – may have 7 tabs open, upload documents, tabs open – when that error comes up – is there a limit to tabs before crashes? On average ~10 complaint cases open",
    "Managing multiple tools – is that frustrating? Could be a more efficient way to have all the things they use. Shawn: very analog so doesn’t know what that would look like GIS map",
    "Deed search – if inspectors listed with parcel info",
    "Would save time if all info on catchment map were in IPS on the parcel – but still wouldn’t have geographic context",
    "M: Pixel perfect when searching by address in AS400 – very difficult, functionality atrocious, like the aesthetic",
    "J: AS400 – uses it for water billing, goes to view wtr history and won’t go anywhere – will go ‘long way’ - additional 3 steps – even then sometimes it’s not there",
    "Only more annoying because",
    "Kevin gave long list of address changes – updating owner addresses in AS400 and in IPS",
    "Updating address only annoying",
    "Death certificate 2003 of someone trying to serve",
    "Can they have assessment update the address?",
    "IPS doesn’t allow saving owner addresses sometimes – or permission based? Tim could do it",
    "Sheer amount of duplicates in address book in IPS and AS400 – some of that is the owner addresses themselves",
    "With LLCs do have to keep it distinct if multiple LLCs so not all within our control",
    "Put in contact information – enter someone with same name, address book won’t let you enter it if it’s similar – e.g. enter same name but different address",
    "Assessment change of address form – share",
    "Anything you like about IPS",
    "Automatically adds hypens with phone number",
    "Appreciates that within parcel, can click on button that brings directly to Image Mate with the owner address",
    "Dark mode for IPS?  +2 Incredibly bright",
    "Other information you wish were available or features/capabailities?",
    "Spell check or grammar check",
    "Not consistent – some parts have features and others don’t",
    "If everything could be more easily identifiable on the thumbnails – when you pull ip the Parcel History, not easy to tell e..g large complexes like Nob Hill, has to open each individually to find apartment – make it more identifiable e.g. apartment, unit – only has status, open date",
    "Finding/opening specific cases difficult",
    "Computer is slow – takes 45 sec to open complaint case",
    "When you open a case note on an already open case – sometimes your name isn’t there – blank space – sometimes only inspectors are there",
    "Some things you need to hit Save and other time you don’t need to",
    "Save button never in the same place or",
    "New next to Save and look the same",
    "Notepads, a lot of Excel documents",
    "S: Doesn’t use Excel on day to day",
    "Made cheat sheets and phone lists of commonly ysed things – reference docs",
    "Deed search, GIS,",
    "MS Teams: will contact cityline Christine Norween",
    "Inspectors update SeeClick Fix – not admin aides",
    "Mondays are the busiest – 9 or 3pm",
    "Closing/Next Steps | 5min | Rose"
  ],
  "DOCE Discovery Session | Building Inspectors Group 1": [
    "Introductions",
    "Rob Melcher: Housing > Building - 5yrs",
    "Ashlie: Clerk > Admin Supervisor > Housing > Building - 20yrs",
    "Dan: Housing > Building – 2018 (8 yrs)",
    "Reggie: Housing > Building (4 yrs) - 2019 (7 yrs)",
    "Luke: Vacants (separate dept at the time, just him and Ryan) - 23yrs",
    "Share Out",
    "Role",
    "Building inspecor: CofC, CofU, Zoning, permits, tobacco, CofA, CofI, permit inspections – floaters for now if they’re booked up",
    "Gave it to certain inspectors",
    "Process",
    "Intake/scheduling",
    "Depends on the inspection",
    "CofU – Corinne gets applications and she schedules",
    "CofC – Anthony and Maria – application side – call and schedule (doesn’t always happen)",
    "May be due for CofC before app even comes up, and inspector will start",
    "CofU/CofI – Fire and electrical",
    "Sometimes Fire does their own thing",
    "Aides schedule CofU – can be diconnect between Fire and inspector going",
    "Outlook, IPS, Outlook calendar – doesn't even",
    "Inspections",
    "Electrical test, camera in iPhone for photos",
    "Got tablets years ago – great idea, too much lag – heard that IT didn’t want to pay for updates on tablets",
    "Restricts them in the field - don't know what’s cited",
    "Reggie’s tablet does work – needs hotspots to work",
    "Photos go right into case – notes go in straighaway",
    "IPhones were great when they got them",
    "IPads with IPS app are droid companability – doesn't work with iPhones",
    "Taking notes on paper and picture on phone",
    "Before go out – checking out what’s required, whether they need dust wipes (lead)",
    "Back in the office – type up notes",
    "End of the day – depends on number of cases and violations",
    "Doing it in the field would save a ton of time",
    "Send themsevles",
    "Got them new tablets – first day doesn’t work",
    "Case management",
    "Daily workload and total workload",
    "You set up your own tickle date – not automated",
    "You have red to know if you’re really behind",
    "If you forgot to put tickle date in – cases are lost",
    "IPS crashes – 3 or 4 cases – someone calls – may have lost your case – doesn't save session",
    "BAA process",
    "In an area where people get scared with the notices",
    "Rollover – if taxes unpaid, can’t get CofC",
    "Not supposed to issue cert with taxes – can issue if in tax trust",
    "PO lie all the time – Assmt",
    "Different info from different departments",
    "Can’t send PO to BAA if tax delinquent per – if only thing is CofC being held up",
    "Pain Points & Challenges",
    "Rob: Zoning approval – Zone checks take forever – he knows they’re very busy",
    "Can’t issue without zone check, they don’t update IPS case",
    "Other depts that get involved – don't update IPS with notes, can be an issue",
    "Inspectors are point of contact – get people calling – waiting for BAA, Law or Zoning",
    "Nob Hill – cited over 2 years ago for elevators – due in 2019",
    "Ashlie - she didn’t know they were – can't cite if don’t know it’s expired",
    "Referred to Law in May 2024",
    "DOCE get blamed a lot",
    "2 years since it’s been referred to Law and no note from Law",
    "Inspectors aren’t updated with info when cases are in court even some times – gets info from syracuse.com",
    "Third-party inspectors: Sprinklers, fire alarm, smoke certs if hardwired, boilers/furnace, HVAC, elevators",
    "Will put reports to fire marshal and they will review and approve",
    "Only a few have access to Compliance Engine to look it up",
    "Water check – gets another inspector to look up the water movement",
    "Difficult for AS400 to use",
    "Technology",
    "See the water and elevator certs – have to ask Sonya – no note if it’s passed or paid",
    "i.e. Can’t finish the CofC application until that’s in",
    "Tools – Camino for permits",
    "Can read notes from owners",
    "Mainly checking if doing work without a permit",
    "Also where applications come in for CofCs",
    "May check on whether they’re pulling permits, whether its passed",
    "Wait on zoning again",
    "Approvals for CofUs – redtape owners need to go through – slows down the process – DPW, zoning, Law, police",
    "IPS – likes",
    "Tickle dates – reminder dates are helpful",
    "Too many cases that they manage",
    "Ashlie – liked AS400 – had everything in there",
    "Now hopping back and forth",
    "Likes that all documents and images are saved in there – even communication with owner",
    "With BAA, have to provide pictures",
    "Photos also helpful for inspectors – compare/contrast",
    "Options for actions in IPS – everything all in there",
    "If you’re interrupted",
    "AS400 you can look up missed assignments",
    "Couldn’t save documents in there – had to go into Onbase",
    "Likes it for certain things, doesn’t like it for others",
    "Ashlie started as paralegal – between Codes and Law – also a clerk – started with RR program – easier for her, can look anything up",
    "IPS – can search for anything",
    "Issue for clerks as well – Nob Hill eg. Huge list of cases – issue with searching – sift through all of those cases",
    "Anthony – add CofC case apps, gets added to older cases",
    "DPW had their own cases in IPS when they first started – older cases",
    "Fire will also start their own cases in IPS – they don’t follow up on it – now inspectors do it for them",
    "County lead in there too – can see it – but makes more cases",
    "IPS – ownership issues",
    "IPS updates itself",
    "Multiple owners in Address Book – has to go in as multiple entries even if the same individual",
    "Reggie’s case changed – he tries to change the older – causes confusion, multiple listed",
    "If you try to delete causes issues",
    "BAS said nothing they can do about it",
    "So many places something can be put in – which ones is the correct updated ownership, phone numbers, etc. - and which was last put in is not indicated",
    "Multiple ways to update in system – if not updated in certain way, doesn’t get",
    "AS400 checks 4 way – Ashlie uses constantly, Rob not familiar with it",
    "Used to be trained on it day one",
    "Don’t use spreadsheets – but supervisors do",
    "Tracking",
    "Features or capabilities you wish IPS had",
    "When it crashes – if it could refresh with where you are",
    "Happens often – too many windows open",
    "Letters admin aides think it’s an issue– if doing same thing at the same time",
    "Same property – multiple cases",
    "See high-risk area from IPS parcel area",
    "Catchment map",
    "Be nice if IPS had everything they needed – now we have so many apps",
    "Sonya elevators, catchment map, Camino, Compliance Engine",
    "Tablet that connects – idea is great",
    "Ashlie had skyline at the time – 45 minutes to pull up cases",
    "More info cases in IPS harder it would be to",
    "Offline capability – if they go into a basement to look at boiler, service drops/tablet wouldn’t work",
    "Would be interesting to see what other municipalities use for software – in NYS same codes",
    "Ashlie has high hopes – this meeting longer already than the one they held when picking IPS (Gretchen in Law? At the time)",
    "Luke: Codes wasn’t consulted",
    "Items Dan M. followed up with via email 2026-05-26:",
    "Some of the inspectors do not have the ability to delete actions or photos in IPS if they are added by mistake. A lot of them come to me to do that for them.",
    "Several inspectors do not have access to AS400. We do need this to check for proper ownership as well as water usage to determine vacancy."
  ],
  "DOCE Discovery Session | Admin Aides Group 2": [
    "Introductions",
    "Eric, Admin Aide, 2024",
    "Lillian, Admin Aide, 2024",
    "Share Out",
    "Role",
    "Mostly make calls, schedule complaints, schedule inspections – bulk of what they do",
    "Grab things from the printer – mailings from printer",
    "Rent holds and rent releases – occur every day – not all working on all at the same time",
    "Lillian: Point of contact – general public that comes in – her or Maria handle the spanish speaking population and handle inspections for them upstairs (if Maria not there may help out downstairs or Suehaly or Jenifer from SPD)",
    "Speak to inspectors, or Land Bank or zoning plans examiners",
    "Gets overwhelming – just one window",
    "Someone calls trying to schedule inspection or PO wants information – just one window – gets congested",
    "People showing up a lot and calling a lot",
    "Handling voicemails and callbacks",
    "Issues with phones – started 2-3 months – phone calls just drop – people frustrated because phone drops – IT tickets on it since 2024",
    "They don’t just get CE phone calls – field calls for multiple departments – get calls for cityline or DPW – get a lot of phone traffic",
    "Try to direct them to departments – those departments don’t pick up the phone – try to give them an alternative solution i.e. fill out form",
    "Website – tried to create a ticket through seeclickfix – got a blank screen*",
    "Tools",
    "IPS, phones, Caminos",
    "Camino is the smoothest – up-to-date, reliable – runs well compared to everything else",
    "Sometimes don’t upload the inspectors",
    "AS400 – water notes, update ownership records, taxes",
    "Katelyn uses it the most",
    "Don’t track things mostly outside of IPS",
    "Outlook",
    "Tim monitors main codes email",
    "Will send copies of things through their emails – send a lot of attachments",
    "They use spreadsheets scarcily – only one recently",
    "Collaboration with other depts",
    "Use Teams or use phone extensions",
    "Document a lot in IPS just to make sure it’s there",
    "If in the office, visit in person",
    "Process",
    "Pain Points & Challenges",
    "Would be nice for a section specifically for Law/legal",
    "7D court filings – don't have a dedicated place for this – would be nice if legal had their own section for it. If no case, adding to other general attachments – a lot in there – their own designated space for it to be uploaded",
    "IPS: when trying to save anything – brink of crashing – slows down – loading window – if crashes, will say out of memory",
    "Periodic inspections module: Issue with inspector names not sorting alphabetize",
    "Everything else runs pretty smoothly – mainly processing speed",
    "If updating nail and mails – sometimes you can’t upload the document",
    "Issue with feature – put in a complaint under building without a permit – when it times to send out letter *follow up with Tim for details",
    "Mainly put under Prop Maint Int/Ext - would be more recognizable as Bldg w/o a Permit",
    "Katelyn creates tickets",
    "Re: mailing a letter out - Sometimes can’t find the new owner in the system – go into county clerk’s deeds and mortgages",
    "Can’t find new owners – creates an issue because old owners calls us, become aggravated/agitated because they sold it",
    "Collaboration with other departments?",
    "When waiting on approval for something – if they can’t get ahold of Permits office",
    "Eric: Likes that everything is in Camino – database for that",
    "Multiple tools they have to handle – would be nice if something that collected those data and inputted in both systems",
    "AS400: Do use it often, very outdated",
    "Lillian not really trained on AS400",
    "Technology",
    "Features you like/that work well",
    "Likes periodics window for Rental Registry",
    "Documents on one side, inspection on the other side, add notes to it specifically",
    "PI module layout – likes it better than the complaint module – designed well – when you click on date, doesn’t calendar – very useful",
    "Likes the layout",
    "Only complaint is the list alphabetize",
    "Can see contact phone numbers",
    "That needs to be updated",
    "Owner/contact information – needs to be connected – updated individually in RR module vs complaint module",
    "Attachment for CofUs – don't see it in the attachments",
    "Mention to Tom?",
    "Anything you wish IPS had?",
    "Would it be possible for them to add licenses? Tab for that",
    "Make it easier to find",
    "Main place where parcel is",

In [87]:
flattened_data = [
    (key, value_index, value)
    for key, values in records.items()
    for value_index, value in enumerate(values)
]
df_export = pd.DataFrame(flattened_data, columns=['Focus Group', 'Value Index', 'Content'])
df_export

,Focus Group,Value Index,Content
0,7DOCE Discovery Session | Admin Aides Group 1,0,"Jordan – Office Manager, 5mos"
1,7DOCE Discovery Session | Admin Aides Group 1,1,"Mastajah – Admin Aides, 6mos (ma-sta-jah)"
2,7DOCE Discovery Session | Admin Aides Group 1,2,"Shawna – Admin Aide, 1.5yr"
3,7DOCE Discovery Session | Admin Aides Group 1,3,Worksheet | 15min | Swapnil
4,7DOCE Discovery Session | Admin Aides Group 1,4,"Share Out* | 40 min | Swapnil facilitates, Ros..."
...,...,...,...
1623,NBD Discovery Session | NBD Data Team,43,"C: workflow designer, excel, argis, seperate a..."
1624,NBD Discovery Session | NBD Data Team,44,"R: external data sources, NY open data portal,..."
1625,NBD Discovery Session | NBD Data Team,45,J: Camino needs the training & support and IPS...
1626,NBD Discovery Session | NBD Data Team,46,R: better case management tool for tailored to...
1627,NBD Discovery Session | NBD Data Team,47,"Software to interface with public, how sylode ..."

In [88]:
# save the traceable export dataframe to a new CSV file
df_export.to_csv("record_mapping.csv", index=False)

In [117]:
def find_using_keywords(keywords, required_word=None):
    if not isinstance(keywords, list):
        raise ValueError("Keywords should be provided as a list.")

    if required_word is not None and not isinstance(required_word, str):
        raise ValueError("required_word should be a string or None.")

    def matches(text):
        text = str(text).lower()
        keywords_match = any(keyword.lower() in text for keyword in keywords)
        required_match = True if required_word is None else required_word.lower() in text
        return keywords_match and required_match

    mask = df_export['Content'].apply(matches)
    filtered_df = df_export[mask]
    return filtered_df

In [116]:
find_using_keywords(["crash", "freez"], "IPS")

Empty DataFrame
Columns: [Focus Group, Value Index, Content]
Index: []